// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace TencentCloudIAC.PulumiPackage.Tencentcloud.Cdwpg.Outputs
{

    [OutputType]
    public sealed class GetLogErrorLogDetailResult
    {
        /// <summary>
        /// Database.
        /// </summary>
        public readonly string Database;
        /// <summary>
        /// Error message.
        /// </summary>
        public readonly string ErrorMessage;
        /// <summary>
        /// Error time.
        /// </summary>
        public readonly string ErrorTime;
        /// <summary>
        /// Username.
        /// </summary>
        public readonly string UserName;

        [OutputConstructor]
        private GetLogErrorLogDetailResult(
            string database,

            string errorMessage,

            string errorTime,

            string userName)
        {
            Database = database;
            ErrorMessage = errorMessage;
            ErrorTime = errorTime;
            UserName = userName;
        }
    }
}
