# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

__all__ = [
    'GetGroupMembershipsResult',
    'AwaitableGetGroupMembershipsResult',
    'get_group_memberships',
    'get_group_memberships_output',
]

@pulumi.output_type
class GetGroupMembershipsResult:
    """
    A collection of values returned by getGroupMemberships.
    """
    def __init__(__self__, group_id=None, id=None, membership_lists=None, result_output_file=None):
        if group_id and not isinstance(group_id, str):
            raise TypeError("Expected argument 'group_id' to be a str")
        pulumi.set(__self__, "group_id", group_id)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if membership_lists and not isinstance(membership_lists, list):
            raise TypeError("Expected argument 'membership_lists' to be a list")
        pulumi.set(__self__, "membership_lists", membership_lists)
        if result_output_file and not isinstance(result_output_file, str):
            raise TypeError("Expected argument 'result_output_file' to be a str")
        pulumi.set(__self__, "result_output_file", result_output_file)

    @_builtins.property
    @pulumi.getter(name="groupId")
    def group_id(self) -> Optional[_builtins.str]:
        """
        ID of CAM group.
        """
        return pulumi.get(self, "group_id")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="membershipLists")
    def membership_lists(self) -> Sequence['outputs.GetGroupMembershipsMembershipListResult']:
        """
        A list of CAM group membership. Each element contains the following attributes:
        """
        return pulumi.get(self, "membership_lists")

    @_builtins.property
    @pulumi.getter(name="resultOutputFile")
    def result_output_file(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "result_output_file")


class AwaitableGetGroupMembershipsResult(GetGroupMembershipsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetGroupMembershipsResult(
            group_id=self.group_id,
            id=self.id,
            membership_lists=self.membership_lists,
            result_output_file=self.result_output_file)


def get_group_memberships(group_id: Optional[_builtins.str] = None,
                          result_output_file: Optional[_builtins.str] = None,
                          opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetGroupMembershipsResult:
    """
    Use this data source to query detailed information of CAM group memberships

    ## Example Usage

    ```python
    import pulumi
    import pulumi_tencentcloud as tencentcloud

    foo = tencentcloud.Cam.get_group_memberships(group_id=foo_tencentcloud_cam_group["id"])
    ```


    :param _builtins.str group_id: ID of CAM group to be queried.
    :param _builtins.str result_output_file: Used to save results.
    """
    __args__ = dict()
    __args__['groupId'] = group_id
    __args__['resultOutputFile'] = result_output_file
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('tencentcloud:Cam/getGroupMemberships:getGroupMemberships', __args__, opts=opts, typ=GetGroupMembershipsResult).value

    return AwaitableGetGroupMembershipsResult(
        group_id=pulumi.get(__ret__, 'group_id'),
        id=pulumi.get(__ret__, 'id'),
        membership_lists=pulumi.get(__ret__, 'membership_lists'),
        result_output_file=pulumi.get(__ret__, 'result_output_file'))
def get_group_memberships_output(group_id: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                 result_output_file: Optional[pulumi.Input[Optional[_builtins.str]]] = None,
                                 opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetGroupMembershipsResult]:
    """
    Use this data source to query detailed information of CAM group memberships

    ## Example Usage

    ```python
    import pulumi
    import pulumi_tencentcloud as tencentcloud

    foo = tencentcloud.Cam.get_group_memberships(group_id=foo_tencentcloud_cam_group["id"])
    ```


    :param _builtins.str group_id: ID of CAM group to be queried.
    :param _builtins.str result_output_file: Used to save results.
    """
    __args__ = dict()
    __args__['groupId'] = group_id
    __args__['resultOutputFile'] = result_output_file
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('tencentcloud:Cam/getGroupMemberships:getGroupMemberships', __args__, opts=opts, typ=GetGroupMembershipsResult)
    return __ret__.apply(lambda __response__: GetGroupMembershipsResult(
        group_id=pulumi.get(__response__, 'group_id'),
        id=pulumi.get(__response__, 'id'),
        membership_lists=pulumi.get(__response__, 'membership_lists'),
        result_output_file=pulumi.get(__response__, 'result_output_file')))
