# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import sys
from collections.abc import Mapping
from typing import overload

import pulumi
import pulumi.runtime

if sys.version_info >= (3, 11):
    pass
else:
    pass
from .. import _utilities

__all__ = ["User", "UserArgs"]


@pulumi.input_type
class UserArgs:
    def __init__(
        __self__,
        *,
        console_login: pulumi.Input[_builtins.bool | None] = None,
        country_code: pulumi.Input[_builtins.str | None] = None,
        email: pulumi.Input[_builtins.str | None] = None,
        force_delete: pulumi.Input[_builtins.bool | None] = None,
        name: pulumi.Input[_builtins.str | None] = None,
        need_reset_password: pulumi.Input[_builtins.bool | None] = None,
        password: pulumi.Input[_builtins.str | None] = None,
        phone_num: pulumi.Input[_builtins.str | None] = None,
        remark: pulumi.Input[_builtins.str | None] = None,
        tags: pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]] | None] = None,
        use_api: pulumi.Input[_builtins.bool | None] = None
    ):
        """
        The set of arguments for constructing a User resource.

        :param pulumi.Input[_builtins.bool] console_login: Indicate whether the CAM user can login to the web console or not.
        :param pulumi.Input[_builtins.str] country_code: Country code of the phone number, for example: '86'.
        :param pulumi.Input[_builtins.str] email: Email of the CAM user.
        :param pulumi.Input[_builtins.bool] force_delete: Indicate whether to force deletes the CAM user. If set false, the API secret key will be checked and failed when exists; otherwise the user will be deleted directly. Default is false.
        :param pulumi.Input[_builtins.str] name: Name of the CAM user.
        :param pulumi.Input[_builtins.bool] need_reset_password: Indicate whether the CAM user need to reset the password when first logins.
        :param pulumi.Input[_builtins.str] password: The password of the CAM user. Password should be at least 8 characters and no more than 32 characters, includes uppercase letters, lowercase letters, numbers and special characters. Only required when `console_login` is true. If not set, a random password will be automatically generated.
        :param pulumi.Input[_builtins.str] phone_num: Phone number of the CAM user.
        :param pulumi.Input[_builtins.str] remark: Remark of the CAM user.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: A list of tags used to associate different resources.
        :param pulumi.Input[_builtins.bool] use_api: Indicate whether to generate the API secret key or not.
        """
        if console_login is not None:
            pulumi.set(__self__, "console_login", console_login)
        if country_code is not None:
            pulumi.set(__self__, "country_code", country_code)
        if email is not None:
            pulumi.set(__self__, "email", email)
        if force_delete is not None:
            pulumi.set(__self__, "force_delete", force_delete)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if need_reset_password is not None:
            pulumi.set(__self__, "need_reset_password", need_reset_password)
        if password is not None:
            pulumi.set(__self__, "password", password)
        if phone_num is not None:
            pulumi.set(__self__, "phone_num", phone_num)
        if remark is not None:
            pulumi.set(__self__, "remark", remark)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if use_api is not None:
            pulumi.set(__self__, "use_api", use_api)

    @_builtins.property
    @pulumi.getter(name="consoleLogin")
    def console_login(self) -> pulumi.Input[_builtins.bool | None]:
        """
        Indicate whether the CAM user can login to the web console or not.
        """
        return pulumi.get(self, "console_login")

    @console_login.setter
    def console_login(self, value: pulumi.Input[_builtins.bool | None]):
        pulumi.set(self, "console_login", value)

    @_builtins.property
    @pulumi.getter(name="countryCode")
    def country_code(self) -> pulumi.Input[_builtins.str | None]:
        """
        Country code of the phone number, for example: '86'.
        """
        return pulumi.get(self, "country_code")

    @country_code.setter
    def country_code(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "country_code", value)

    @_builtins.property
    @pulumi.getter
    def email(self) -> pulumi.Input[_builtins.str | None]:
        """
        Email of the CAM user.
        """
        return pulumi.get(self, "email")

    @email.setter
    def email(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "email", value)

    @_builtins.property
    @pulumi.getter(name="forceDelete")
    def force_delete(self) -> pulumi.Input[_builtins.bool | None]:
        """
        Indicate whether to force deletes the CAM user. If set false, the API secret key will be checked and failed when exists; otherwise the user will be deleted directly. Default is false.
        """
        return pulumi.get(self, "force_delete")

    @force_delete.setter
    def force_delete(self, value: pulumi.Input[_builtins.bool | None]):
        pulumi.set(self, "force_delete", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str | None]:
        """
        Name of the CAM user.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="needResetPassword")
    def need_reset_password(self) -> pulumi.Input[_builtins.bool | None]:
        """
        Indicate whether the CAM user need to reset the password when first logins.
        """
        return pulumi.get(self, "need_reset_password")

    @need_reset_password.setter
    def need_reset_password(self, value: pulumi.Input[_builtins.bool | None]):
        pulumi.set(self, "need_reset_password", value)

    @_builtins.property
    @pulumi.getter
    def password(self) -> pulumi.Input[_builtins.str | None]:
        """
        The password of the CAM user. Password should be at least 8 characters and no more than 32 characters, includes uppercase letters, lowercase letters, numbers and special characters. Only required when `console_login` is true. If not set, a random password will be automatically generated.
        """
        return pulumi.get(self, "password")

    @password.setter
    def password(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "password", value)

    @_builtins.property
    @pulumi.getter(name="phoneNum")
    def phone_num(self) -> pulumi.Input[_builtins.str | None]:
        """
        Phone number of the CAM user.
        """
        return pulumi.get(self, "phone_num")

    @phone_num.setter
    def phone_num(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "phone_num", value)

    @_builtins.property
    @pulumi.getter
    def remark(self) -> pulumi.Input[_builtins.str | None]:
        """
        Remark of the CAM user.
        """
        return pulumi.get(self, "remark")

    @remark.setter
    def remark(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "remark", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]] | None]:
        """
        A list of tags used to associate different resources.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(
        self, value: pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]] | None]
    ):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="useApi")
    def use_api(self) -> pulumi.Input[_builtins.bool | None]:
        """
        Indicate whether to generate the API secret key or not.
        """
        return pulumi.get(self, "use_api")

    @use_api.setter
    def use_api(self, value: pulumi.Input[_builtins.bool | None]):
        pulumi.set(self, "use_api", value)


@pulumi.input_type
class _UserState:
    def __init__(
        __self__,
        *,
        console_login: pulumi.Input[_builtins.bool | None] = None,
        country_code: pulumi.Input[_builtins.str | None] = None,
        email: pulumi.Input[_builtins.str | None] = None,
        force_delete: pulumi.Input[_builtins.bool | None] = None,
        name: pulumi.Input[_builtins.str | None] = None,
        need_reset_password: pulumi.Input[_builtins.bool | None] = None,
        password: pulumi.Input[_builtins.str | None] = None,
        phone_num: pulumi.Input[_builtins.str | None] = None,
        remark: pulumi.Input[_builtins.str | None] = None,
        secret_id: pulumi.Input[_builtins.str | None] = None,
        secret_key: pulumi.Input[_builtins.str | None] = None,
        tags: pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]] | None] = None,
        uid: pulumi.Input[_builtins.int | None] = None,
        uin: pulumi.Input[_builtins.int | None] = None,
        use_api: pulumi.Input[_builtins.bool | None] = None
    ):
        """
        Input properties used for looking up and filtering User resources.

        :param pulumi.Input[_builtins.bool] console_login: Indicate whether the CAM user can login to the web console or not.
        :param pulumi.Input[_builtins.str] country_code: Country code of the phone number, for example: '86'.
        :param pulumi.Input[_builtins.str] email: Email of the CAM user.
        :param pulumi.Input[_builtins.bool] force_delete: Indicate whether to force deletes the CAM user. If set false, the API secret key will be checked and failed when exists; otherwise the user will be deleted directly. Default is false.
        :param pulumi.Input[_builtins.str] name: Name of the CAM user.
        :param pulumi.Input[_builtins.bool] need_reset_password: Indicate whether the CAM user need to reset the password when first logins.
        :param pulumi.Input[_builtins.str] password: The password of the CAM user. Password should be at least 8 characters and no more than 32 characters, includes uppercase letters, lowercase letters, numbers and special characters. Only required when `console_login` is true. If not set, a random password will be automatically generated.
        :param pulumi.Input[_builtins.str] phone_num: Phone number of the CAM user.
        :param pulumi.Input[_builtins.str] remark: Remark of the CAM user.
        :param pulumi.Input[_builtins.str] secret_id: Secret ID of the CAM user.
        :param pulumi.Input[_builtins.str] secret_key: Secret key of the CAM user.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: A list of tags used to associate different resources.
        :param pulumi.Input[_builtins.int] uid: ID of the CAM user.
        :param pulumi.Input[_builtins.int] uin: Uin of the CAM User.
        :param pulumi.Input[_builtins.bool] use_api: Indicate whether to generate the API secret key or not.
        """
        if console_login is not None:
            pulumi.set(__self__, "console_login", console_login)
        if country_code is not None:
            pulumi.set(__self__, "country_code", country_code)
        if email is not None:
            pulumi.set(__self__, "email", email)
        if force_delete is not None:
            pulumi.set(__self__, "force_delete", force_delete)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if need_reset_password is not None:
            pulumi.set(__self__, "need_reset_password", need_reset_password)
        if password is not None:
            pulumi.set(__self__, "password", password)
        if phone_num is not None:
            pulumi.set(__self__, "phone_num", phone_num)
        if remark is not None:
            pulumi.set(__self__, "remark", remark)
        if secret_id is not None:
            pulumi.set(__self__, "secret_id", secret_id)
        if secret_key is not None:
            pulumi.set(__self__, "secret_key", secret_key)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if uid is not None:
            pulumi.set(__self__, "uid", uid)
        if uin is not None:
            pulumi.set(__self__, "uin", uin)
        if use_api is not None:
            pulumi.set(__self__, "use_api", use_api)

    @_builtins.property
    @pulumi.getter(name="consoleLogin")
    def console_login(self) -> pulumi.Input[_builtins.bool | None]:
        """
        Indicate whether the CAM user can login to the web console or not.
        """
        return pulumi.get(self, "console_login")

    @console_login.setter
    def console_login(self, value: pulumi.Input[_builtins.bool | None]):
        pulumi.set(self, "console_login", value)

    @_builtins.property
    @pulumi.getter(name="countryCode")
    def country_code(self) -> pulumi.Input[_builtins.str | None]:
        """
        Country code of the phone number, for example: '86'.
        """
        return pulumi.get(self, "country_code")

    @country_code.setter
    def country_code(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "country_code", value)

    @_builtins.property
    @pulumi.getter
    def email(self) -> pulumi.Input[_builtins.str | None]:
        """
        Email of the CAM user.
        """
        return pulumi.get(self, "email")

    @email.setter
    def email(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "email", value)

    @_builtins.property
    @pulumi.getter(name="forceDelete")
    def force_delete(self) -> pulumi.Input[_builtins.bool | None]:
        """
        Indicate whether to force deletes the CAM user. If set false, the API secret key will be checked and failed when exists; otherwise the user will be deleted directly. Default is false.
        """
        return pulumi.get(self, "force_delete")

    @force_delete.setter
    def force_delete(self, value: pulumi.Input[_builtins.bool | None]):
        pulumi.set(self, "force_delete", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str | None]:
        """
        Name of the CAM user.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="needResetPassword")
    def need_reset_password(self) -> pulumi.Input[_builtins.bool | None]:
        """
        Indicate whether the CAM user need to reset the password when first logins.
        """
        return pulumi.get(self, "need_reset_password")

    @need_reset_password.setter
    def need_reset_password(self, value: pulumi.Input[_builtins.bool | None]):
        pulumi.set(self, "need_reset_password", value)

    @_builtins.property
    @pulumi.getter
    def password(self) -> pulumi.Input[_builtins.str | None]:
        """
        The password of the CAM user. Password should be at least 8 characters and no more than 32 characters, includes uppercase letters, lowercase letters, numbers and special characters. Only required when `console_login` is true. If not set, a random password will be automatically generated.
        """
        return pulumi.get(self, "password")

    @password.setter
    def password(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "password", value)

    @_builtins.property
    @pulumi.getter(name="phoneNum")
    def phone_num(self) -> pulumi.Input[_builtins.str | None]:
        """
        Phone number of the CAM user.
        """
        return pulumi.get(self, "phone_num")

    @phone_num.setter
    def phone_num(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "phone_num", value)

    @_builtins.property
    @pulumi.getter
    def remark(self) -> pulumi.Input[_builtins.str | None]:
        """
        Remark of the CAM user.
        """
        return pulumi.get(self, "remark")

    @remark.setter
    def remark(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "remark", value)

    @_builtins.property
    @pulumi.getter(name="secretId")
    def secret_id(self) -> pulumi.Input[_builtins.str | None]:
        """
        Secret ID of the CAM user.
        """
        return pulumi.get(self, "secret_id")

    @secret_id.setter
    def secret_id(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "secret_id", value)

    @_builtins.property
    @pulumi.getter(name="secretKey")
    def secret_key(self) -> pulumi.Input[_builtins.str | None]:
        """
        Secret key of the CAM user.
        """
        return pulumi.get(self, "secret_key")

    @secret_key.setter
    def secret_key(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "secret_key", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]] | None]:
        """
        A list of tags used to associate different resources.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(
        self, value: pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]] | None]
    ):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter
    def uid(self) -> pulumi.Input[_builtins.int | None]:
        """
        ID of the CAM user.
        """
        return pulumi.get(self, "uid")

    @uid.setter
    def uid(self, value: pulumi.Input[_builtins.int | None]):
        pulumi.set(self, "uid", value)

    @_builtins.property
    @pulumi.getter
    def uin(self) -> pulumi.Input[_builtins.int | None]:
        """
        Uin of the CAM User.
        """
        return pulumi.get(self, "uin")

    @uin.setter
    def uin(self, value: pulumi.Input[_builtins.int | None]):
        pulumi.set(self, "uin", value)

    @_builtins.property
    @pulumi.getter(name="useApi")
    def use_api(self) -> pulumi.Input[_builtins.bool | None]:
        """
        Indicate whether to generate the API secret key or not.
        """
        return pulumi.get(self, "use_api")

    @use_api.setter
    def use_api(self, value: pulumi.Input[_builtins.bool | None]):
        pulumi.set(self, "use_api", value)


@pulumi.type_token("tencentcloud:Cam/user:User")
class User(pulumi.CustomResource):
    @overload
    def __init__(
        __self__,
        resource_name: str,
        opts: pulumi.ResourceOptions | None = None,
        console_login: pulumi.Input[_builtins.bool | None] = None,
        country_code: pulumi.Input[_builtins.str | None] = None,
        email: pulumi.Input[_builtins.str | None] = None,
        force_delete: pulumi.Input[_builtins.bool | None] = None,
        name: pulumi.Input[_builtins.str | None] = None,
        need_reset_password: pulumi.Input[_builtins.bool | None] = None,
        password: pulumi.Input[_builtins.str | None] = None,
        phone_num: pulumi.Input[_builtins.str | None] = None,
        remark: pulumi.Input[_builtins.str | None] = None,
        tags: pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]] | None] = None,
        use_api: pulumi.Input[_builtins.bool | None] = None,
        __props__=None,
    ):
        """
        Provides a resource to manage CAM user.

        ## Example Usage

        ```python
        import pulumi
        import tencentcloud_iac_pulumi as tencentcloud

        example = tencentcloud.cam.User("example",
            name="tf-example",
            remark="Remark.",
            console_login=True,
            use_api=True,
            need_reset_password=True,
            password="Password@123",
            phone_num="189********",
            email="example@qq.com",
            country_code="86",
            force_delete=True,
            tags={
                "createBy": "Terraform",
            })
        ```

        ## Import

        CAM user can be imported using the user name, e.g.

        ```sh
        $ pulumi import tencentcloud:Cam/user:User example tf-example
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] console_login: Indicate whether the CAM user can login to the web console or not.
        :param pulumi.Input[_builtins.str] country_code: Country code of the phone number, for example: '86'.
        :param pulumi.Input[_builtins.str] email: Email of the CAM user.
        :param pulumi.Input[_builtins.bool] force_delete: Indicate whether to force deletes the CAM user. If set false, the API secret key will be checked and failed when exists; otherwise the user will be deleted directly. Default is false.
        :param pulumi.Input[_builtins.str] name: Name of the CAM user.
        :param pulumi.Input[_builtins.bool] need_reset_password: Indicate whether the CAM user need to reset the password when first logins.
        :param pulumi.Input[_builtins.str] password: The password of the CAM user. Password should be at least 8 characters and no more than 32 characters, includes uppercase letters, lowercase letters, numbers and special characters. Only required when `console_login` is true. If not set, a random password will be automatically generated.
        :param pulumi.Input[_builtins.str] phone_num: Phone number of the CAM user.
        :param pulumi.Input[_builtins.str] remark: Remark of the CAM user.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: A list of tags used to associate different resources.
        :param pulumi.Input[_builtins.bool] use_api: Indicate whether to generate the API secret key or not.
        """

    @overload
    def __init__(
        __self__,
        resource_name: str,
        args: UserArgs | None = None,
        opts: pulumi.ResourceOptions | None = None,
    ):
        """
        Provides a resource to manage CAM user.

        ## Example Usage

        ```python
        import pulumi
        import tencentcloud_iac_pulumi as tencentcloud

        example = tencentcloud.cam.User("example",
            name="tf-example",
            remark="Remark.",
            console_login=True,
            use_api=True,
            need_reset_password=True,
            password="Password@123",
            phone_num="189********",
            email="example@qq.com",
            country_code="86",
            force_delete=True,
            tags={
                "createBy": "Terraform",
            })
        ```

        ## Import

        CAM user can be imported using the user name, e.g.

        ```sh
        $ pulumi import tencentcloud:Cam/user:User example tf-example
        ```


        :param str resource_name: The name of the resource.
        :param UserArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """

    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(
            UserArgs, pulumi.ResourceOptions, *args, **kwargs
        )
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(
        __self__,
        resource_name: str,
        opts: pulumi.ResourceOptions | None = None,
        console_login: pulumi.Input[_builtins.bool | None] = None,
        country_code: pulumi.Input[_builtins.str | None] = None,
        email: pulumi.Input[_builtins.str | None] = None,
        force_delete: pulumi.Input[_builtins.bool | None] = None,
        name: pulumi.Input[_builtins.str | None] = None,
        need_reset_password: pulumi.Input[_builtins.bool | None] = None,
        password: pulumi.Input[_builtins.str | None] = None,
        phone_num: pulumi.Input[_builtins.str | None] = None,
        remark: pulumi.Input[_builtins.str | None] = None,
        tags: pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]] | None] = None,
        use_api: pulumi.Input[_builtins.bool | None] = None,
        __props__=None,
    ):
        opts = pulumi.ResourceOptions.merge(
            _utilities.get_resource_opts_defaults(), opts
        )
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError(
                "Expected resource options to be a ResourceOptions instance"
            )
        if opts.id is None:
            if __props__ is not None:
                raise TypeError(
                    "__props__ is only valid when passed in combination with a valid opts.id to get an existing resource"
                )
            __props__ = UserArgs.__new__(UserArgs)

            __props__.__dict__["console_login"] = console_login
            __props__.__dict__["country_code"] = country_code
            __props__.__dict__["email"] = email
            __props__.__dict__["force_delete"] = force_delete
            __props__.__dict__["name"] = name
            __props__.__dict__["need_reset_password"] = need_reset_password
            __props__.__dict__["password"] = (
                None if password is None else pulumi.Output.secret(password)
            )
            __props__.__dict__["phone_num"] = phone_num
            __props__.__dict__["remark"] = remark
            __props__.__dict__["tags"] = tags
            __props__.__dict__["use_api"] = use_api
            __props__.__dict__["secret_id"] = None
            __props__.__dict__["secret_key"] = None
            __props__.__dict__["uid"] = None
            __props__.__dict__["uin"] = None
        secret_opts = pulumi.ResourceOptions(
            additional_secret_outputs=["password", "secretId", "secretKey"]
        )
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super().__init__("tencentcloud:Cam/user:User", resource_name, __props__, opts)

    @staticmethod
    def get(
        resource_name: str,
        id: pulumi.Input[str],
        opts: pulumi.ResourceOptions | None = None,
        console_login: pulumi.Input[_builtins.bool | None] = None,
        country_code: pulumi.Input[_builtins.str | None] = None,
        email: pulumi.Input[_builtins.str | None] = None,
        force_delete: pulumi.Input[_builtins.bool | None] = None,
        name: pulumi.Input[_builtins.str | None] = None,
        need_reset_password: pulumi.Input[_builtins.bool | None] = None,
        password: pulumi.Input[_builtins.str | None] = None,
        phone_num: pulumi.Input[_builtins.str | None] = None,
        remark: pulumi.Input[_builtins.str | None] = None,
        secret_id: pulumi.Input[_builtins.str | None] = None,
        secret_key: pulumi.Input[_builtins.str | None] = None,
        tags: pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]] | None] = None,
        uid: pulumi.Input[_builtins.int | None] = None,
        uin: pulumi.Input[_builtins.int | None] = None,
        use_api: pulumi.Input[_builtins.bool | None] = None,
    ) -> "User":
        """
        Get an existing User resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] console_login: Indicate whether the CAM user can login to the web console or not.
        :param pulumi.Input[_builtins.str] country_code: Country code of the phone number, for example: '86'.
        :param pulumi.Input[_builtins.str] email: Email of the CAM user.
        :param pulumi.Input[_builtins.bool] force_delete: Indicate whether to force deletes the CAM user. If set false, the API secret key will be checked and failed when exists; otherwise the user will be deleted directly. Default is false.
        :param pulumi.Input[_builtins.str] name: Name of the CAM user.
        :param pulumi.Input[_builtins.bool] need_reset_password: Indicate whether the CAM user need to reset the password when first logins.
        :param pulumi.Input[_builtins.str] password: The password of the CAM user. Password should be at least 8 characters and no more than 32 characters, includes uppercase letters, lowercase letters, numbers and special characters. Only required when `console_login` is true. If not set, a random password will be automatically generated.
        :param pulumi.Input[_builtins.str] phone_num: Phone number of the CAM user.
        :param pulumi.Input[_builtins.str] remark: Remark of the CAM user.
        :param pulumi.Input[_builtins.str] secret_id: Secret ID of the CAM user.
        :param pulumi.Input[_builtins.str] secret_key: Secret key of the CAM user.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: A list of tags used to associate different resources.
        :param pulumi.Input[_builtins.int] uid: ID of the CAM user.
        :param pulumi.Input[_builtins.int] uin: Uin of the CAM User.
        :param pulumi.Input[_builtins.bool] use_api: Indicate whether to generate the API secret key or not.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _UserState.__new__(_UserState)

        __props__.__dict__["console_login"] = console_login
        __props__.__dict__["country_code"] = country_code
        __props__.__dict__["email"] = email
        __props__.__dict__["force_delete"] = force_delete
        __props__.__dict__["name"] = name
        __props__.__dict__["need_reset_password"] = need_reset_password
        __props__.__dict__["password"] = password
        __props__.__dict__["phone_num"] = phone_num
        __props__.__dict__["remark"] = remark
        __props__.__dict__["secret_id"] = secret_id
        __props__.__dict__["secret_key"] = secret_key
        __props__.__dict__["tags"] = tags
        __props__.__dict__["uid"] = uid
        __props__.__dict__["uin"] = uin
        __props__.__dict__["use_api"] = use_api
        return User(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="consoleLogin")
    def console_login(self) -> pulumi.Output[_builtins.bool | None]:
        """
        Indicate whether the CAM user can login to the web console or not.
        """
        return pulumi.get(self, "console_login")

    @_builtins.property
    @pulumi.getter(name="countryCode")
    def country_code(self) -> pulumi.Output[_builtins.str]:
        """
        Country code of the phone number, for example: '86'.
        """
        return pulumi.get(self, "country_code")

    @_builtins.property
    @pulumi.getter
    def email(self) -> pulumi.Output[_builtins.str | None]:
        """
        Email of the CAM user.
        """
        return pulumi.get(self, "email")

    @_builtins.property
    @pulumi.getter(name="forceDelete")
    def force_delete(self) -> pulumi.Output[_builtins.bool | None]:
        """
        Indicate whether to force deletes the CAM user. If set false, the API secret key will be checked and failed when exists; otherwise the user will be deleted directly. Default is false.
        """
        return pulumi.get(self, "force_delete")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the CAM user.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="needResetPassword")
    def need_reset_password(self) -> pulumi.Output[_builtins.bool | None]:
        """
        Indicate whether the CAM user need to reset the password when first logins.
        """
        return pulumi.get(self, "need_reset_password")

    @_builtins.property
    @pulumi.getter
    def password(self) -> pulumi.Output[_builtins.str]:
        """
        The password of the CAM user. Password should be at least 8 characters and no more than 32 characters, includes uppercase letters, lowercase letters, numbers and special characters. Only required when `console_login` is true. If not set, a random password will be automatically generated.
        """
        return pulumi.get(self, "password")

    @_builtins.property
    @pulumi.getter(name="phoneNum")
    def phone_num(self) -> pulumi.Output[_builtins.str | None]:
        """
        Phone number of the CAM user.
        """
        return pulumi.get(self, "phone_num")

    @_builtins.property
    @pulumi.getter
    def remark(self) -> pulumi.Output[_builtins.str | None]:
        """
        Remark of the CAM user.
        """
        return pulumi.get(self, "remark")

    @_builtins.property
    @pulumi.getter(name="secretId")
    def secret_id(self) -> pulumi.Output[_builtins.str]:
        """
        Secret ID of the CAM user.
        """
        return pulumi.get(self, "secret_id")

    @_builtins.property
    @pulumi.getter(name="secretKey")
    def secret_key(self) -> pulumi.Output[_builtins.str]:
        """
        Secret key of the CAM user.
        """
        return pulumi.get(self, "secret_key")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Mapping[str, _builtins.str] | None]:
        """
        A list of tags used to associate different resources.
        """
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter
    def uid(self) -> pulumi.Output[_builtins.int]:
        """
        ID of the CAM user.
        """
        return pulumi.get(self, "uid")

    @_builtins.property
    @pulumi.getter
    def uin(self) -> pulumi.Output[_builtins.int]:
        """
        Uin of the CAM User.
        """
        return pulumi.get(self, "uin")

    @_builtins.property
    @pulumi.getter(name="useApi")
    def use_api(self) -> pulumi.Output[_builtins.bool | None]:
        """
        Indicate whether to generate the API secret key or not.
        """
        return pulumi.get(self, "use_api")
