// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace TencentCloudIAC.PulumiPackage.Tencentcloud.Vpc.Outputs
{

    [OutputType]
    public sealed class GetInstancesInstanceListResult
    {
        /// <summary>
        /// Filter VPC with this CIDR.
        /// </summary>
        public readonly string CidrBlock;
        /// <summary>
        /// Creation time of VPC.
        /// </summary>
        public readonly string CreateTime;
        /// <summary>
        /// A list of DNS servers which can be used within the VPC.
        /// </summary>
        public readonly ImmutableArray<string> DnsServers;
        /// <summary>
        /// Filter default or no default VPC.
        /// </summary>
        public readonly bool IsDefault;
        /// <summary>
        /// Indicates whether VPC multicast is enabled.
        /// </summary>
        public readonly bool IsMulticast;
        /// <summary>
        /// Name of the VPC to be queried.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// A ID list of subnets within this VPC.
        /// </summary>
        public readonly ImmutableArray<string> SubnetIds;
        /// <summary>
        /// Tags of the VPC to be queried.
        /// </summary>
        public readonly ImmutableDictionary<string, object> Tags;
        /// <summary>
        /// ID of the VPC to be queried.
        /// </summary>
        public readonly string VpcId;

        [OutputConstructor]
        private GetInstancesInstanceListResult(
            string cidrBlock,

            string createTime,

            ImmutableArray<string> dnsServers,

            bool isDefault,

            bool isMulticast,

            string name,

            ImmutableArray<string> subnetIds,

            ImmutableDictionary<string, object> tags,

            string vpcId)
        {
            CidrBlock = cidrBlock;
            CreateTime = createTime;
            DnsServers = dnsServers;
            IsDefault = isDefault;
            IsMulticast = isMulticast;
            Name = name;
            SubnetIds = subnetIds;
            Tags = tags;
            VpcId = vpcId;
        }
    }
}
