// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dcdb

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/tencentcloudstack/pulumi-tencentcloud/sdk/go/tencentcloud/internal"
)

// Use this data source to query detailed information of dcdb shardSpec
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/tencentcloudstack/pulumi-tencentcloud/sdk/go/tencentcloud/dcdb"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := dcdb.GetShardSpec(ctx, &dcdb.GetShardSpecArgs{}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetShardSpec(ctx *pulumi.Context, args *GetShardSpecArgs, opts ...pulumi.InvokeOption) (*GetShardSpecResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetShardSpecResult
	err := ctx.Invoke("tencentcloud:Dcdb/getShardSpec:getShardSpec", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getShardSpec.
type GetShardSpecArgs struct {
	// Used to save results.
	ResultOutputFile *string `pulumi:"resultOutputFile"`
}

// A collection of values returned by getShardSpec.
type GetShardSpecResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id               string  `pulumi:"id"`
	ResultOutputFile *string `pulumi:"resultOutputFile"`
	// list of instance specifications.
	SpecConfigs []GetShardSpecSpecConfig `pulumi:"specConfigs"`
}

func GetShardSpecOutput(ctx *pulumi.Context, args GetShardSpecOutputArgs, opts ...pulumi.InvokeOption) GetShardSpecResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetShardSpecResultOutput, error) {
			args := v.(GetShardSpecArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("tencentcloud:Dcdb/getShardSpec:getShardSpec", args, GetShardSpecResultOutput{}, options).(GetShardSpecResultOutput), nil
		}).(GetShardSpecResultOutput)
}

// A collection of arguments for invoking getShardSpec.
type GetShardSpecOutputArgs struct {
	// Used to save results.
	ResultOutputFile pulumi.StringPtrInput `pulumi:"resultOutputFile"`
}

func (GetShardSpecOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetShardSpecArgs)(nil)).Elem()
}

// A collection of values returned by getShardSpec.
type GetShardSpecResultOutput struct{ *pulumi.OutputState }

func (GetShardSpecResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetShardSpecResult)(nil)).Elem()
}

func (o GetShardSpecResultOutput) ToGetShardSpecResultOutput() GetShardSpecResultOutput {
	return o
}

func (o GetShardSpecResultOutput) ToGetShardSpecResultOutputWithContext(ctx context.Context) GetShardSpecResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetShardSpecResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetShardSpecResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetShardSpecResultOutput) ResultOutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetShardSpecResult) *string { return v.ResultOutputFile }).(pulumi.StringPtrOutput)
}

// list of instance specifications.
func (o GetShardSpecResultOutput) SpecConfigs() GetShardSpecSpecConfigArrayOutput {
	return o.ApplyT(func(v GetShardSpecResult) []GetShardSpecSpecConfig { return v.SpecConfigs }).(GetShardSpecSpecConfigArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetShardSpecResultOutput{})
}
