// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace TencentCloudIAC.PulumiPackage.Tencentcloud.Rum
{
    public static class GetLogExport
    {
        public static Task<GetLogExportResult> InvokeAsync(GetLogExportArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetLogExportResult>("tencentcloud:Rum/getLogExport:getLogExport", args ?? new GetLogExportArgs(), options.WithDefaults());

        public static Output<GetLogExportResult> Invoke(GetLogExportInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetLogExportResult>("tencentcloud:Rum/getLogExport:getLogExport", args ?? new GetLogExportInvokeArgs(), options.WithDefaults());

        public static Output<GetLogExportResult> Invoke(GetLogExportInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetLogExportResult>("tencentcloud:Rum/getLogExport:getLogExport", args ?? new GetLogExportInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetLogExportArgs : global::Pulumi.InvokeArgs
    {
        [Input("endTime", required: true)]
        public string EndTime { get; set; } = null!;

        [Input("fields")]
        private List<string>? _fields;
        public List<string> Fields
        {
            get => _fields ?? (_fields = new List<string>());
            set => _fields = value;
        }

        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        [Input("projectId", required: true)]
        public int ProjectId { get; set; }

        [Input("query", required: true)]
        public string Query { get; set; } = null!;

        [Input("resultOutputFile")]
        public string? ResultOutputFile { get; set; }

        [Input("startTime", required: true)]
        public string StartTime { get; set; } = null!;

        public GetLogExportArgs()
        {
        }
        public static new GetLogExportArgs Empty => new GetLogExportArgs();
    }

    public sealed class GetLogExportInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("endTime", required: true)]
        public Input<string> EndTime { get; set; } = null!;

        [Input("fields")]
        private InputList<string>? _fields;
        public InputList<string> Fields
        {
            get => _fields ?? (_fields = new InputList<string>());
            set => _fields = value;
        }

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("projectId", required: true)]
        public Input<int> ProjectId { get; set; } = null!;

        [Input("query", required: true)]
        public Input<string> Query { get; set; } = null!;

        [Input("resultOutputFile")]
        public Input<string>? ResultOutputFile { get; set; }

        [Input("startTime", required: true)]
        public Input<string> StartTime { get; set; } = null!;

        public GetLogExportInvokeArgs()
        {
        }
        public static new GetLogExportInvokeArgs Empty => new GetLogExportInvokeArgs();
    }


    [OutputType]
    public sealed class GetLogExportResult
    {
        public readonly string EndTime;
        public readonly ImmutableArray<string> Fields;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly int ProjectId;
        public readonly string Query;
        public readonly string Result;
        public readonly string? ResultOutputFile;
        public readonly string StartTime;

        [OutputConstructor]
        private GetLogExportResult(
            string endTime,

            ImmutableArray<string> fields,

            string id,

            string name,

            int projectId,

            string query,

            string result,

            string? resultOutputFile,

            string startTime)
        {
            EndTime = endTime;
            Fields = fields;
            Id = id;
            Name = name;
            ProjectId = projectId;
            Query = query;
            Result = result;
            ResultOutputFile = resultOutputFile;
            StartTime = startTime;
        }
    }
}
