// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cdc

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/tencentcloudstack/pulumi-tencentcloud/sdk/go/tencentcloud/internal"
)

// Use this data source to query detailed information of CDC dedicated cluster instance types
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/tencentcloudstack/pulumi-tencentcloud/sdk/go/tencentcloud/cdc"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := cdc.GetDedicatedClusterInstanceTypes(ctx, &cdc.GetDedicatedClusterInstanceTypesArgs{
//				DedicatedClusterId: "cluster-262n63e8",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetDedicatedClusterInstanceTypes(ctx *pulumi.Context, args *GetDedicatedClusterInstanceTypesArgs, opts ...pulumi.InvokeOption) (*GetDedicatedClusterInstanceTypesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetDedicatedClusterInstanceTypesResult
	err := ctx.Invoke("tencentcloud:Cdc/getDedicatedClusterInstanceTypes:getDedicatedClusterInstanceTypes", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDedicatedClusterInstanceTypes.
type GetDedicatedClusterInstanceTypesArgs struct {
	// Dedicated Cluster ID.
	DedicatedClusterId string `pulumi:"dedicatedClusterId"`
	// Used to save results.
	ResultOutputFile *string `pulumi:"resultOutputFile"`
}

// A collection of values returned by getDedicatedClusterInstanceTypes.
type GetDedicatedClusterInstanceTypesResult struct {
	DedicatedClusterId string `pulumi:"dedicatedClusterId"`
	// Dedicated Cluster Supported InstanceType.
	DedicatedClusterInstanceTypeSets []GetDedicatedClusterInstanceTypesDedicatedClusterInstanceTypeSet `pulumi:"dedicatedClusterInstanceTypeSets"`
	// The provider-assigned unique ID for this managed resource.
	Id               string  `pulumi:"id"`
	ResultOutputFile *string `pulumi:"resultOutputFile"`
}

func GetDedicatedClusterInstanceTypesOutput(ctx *pulumi.Context, args GetDedicatedClusterInstanceTypesOutputArgs, opts ...pulumi.InvokeOption) GetDedicatedClusterInstanceTypesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetDedicatedClusterInstanceTypesResultOutput, error) {
			args := v.(GetDedicatedClusterInstanceTypesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("tencentcloud:Cdc/getDedicatedClusterInstanceTypes:getDedicatedClusterInstanceTypes", args, GetDedicatedClusterInstanceTypesResultOutput{}, options).(GetDedicatedClusterInstanceTypesResultOutput), nil
		}).(GetDedicatedClusterInstanceTypesResultOutput)
}

// A collection of arguments for invoking getDedicatedClusterInstanceTypes.
type GetDedicatedClusterInstanceTypesOutputArgs struct {
	// Dedicated Cluster ID.
	DedicatedClusterId pulumi.StringInput `pulumi:"dedicatedClusterId"`
	// Used to save results.
	ResultOutputFile pulumi.StringPtrInput `pulumi:"resultOutputFile"`
}

func (GetDedicatedClusterInstanceTypesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDedicatedClusterInstanceTypesArgs)(nil)).Elem()
}

// A collection of values returned by getDedicatedClusterInstanceTypes.
type GetDedicatedClusterInstanceTypesResultOutput struct{ *pulumi.OutputState }

func (GetDedicatedClusterInstanceTypesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDedicatedClusterInstanceTypesResult)(nil)).Elem()
}

func (o GetDedicatedClusterInstanceTypesResultOutput) ToGetDedicatedClusterInstanceTypesResultOutput() GetDedicatedClusterInstanceTypesResultOutput {
	return o
}

func (o GetDedicatedClusterInstanceTypesResultOutput) ToGetDedicatedClusterInstanceTypesResultOutputWithContext(ctx context.Context) GetDedicatedClusterInstanceTypesResultOutput {
	return o
}

func (o GetDedicatedClusterInstanceTypesResultOutput) DedicatedClusterId() pulumi.StringOutput {
	return o.ApplyT(func(v GetDedicatedClusterInstanceTypesResult) string { return v.DedicatedClusterId }).(pulumi.StringOutput)
}

// Dedicated Cluster Supported InstanceType.
func (o GetDedicatedClusterInstanceTypesResultOutput) DedicatedClusterInstanceTypeSets() GetDedicatedClusterInstanceTypesDedicatedClusterInstanceTypeSetArrayOutput {
	return o.ApplyT(func(v GetDedicatedClusterInstanceTypesResult) []GetDedicatedClusterInstanceTypesDedicatedClusterInstanceTypeSet {
		return v.DedicatedClusterInstanceTypeSets
	}).(GetDedicatedClusterInstanceTypesDedicatedClusterInstanceTypeSetArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetDedicatedClusterInstanceTypesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetDedicatedClusterInstanceTypesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetDedicatedClusterInstanceTypesResultOutput) ResultOutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetDedicatedClusterInstanceTypesResult) *string { return v.ResultOutputFile }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDedicatedClusterInstanceTypesResultOutput{})
}
