// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";
import * as utilities from "../utilities";

/**
 * Use this data source to query detailed information of waf tlsVersions
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as tencentcloud from "@pulumi/tencentcloud";
 *
 * const example = pulumi.output(tencentcloud.Waf.getTlsVersions());
 * ```
 */
export function getTlsVersions(args?: GetTlsVersionsArgs, opts?: pulumi.InvokeOptions): Promise<GetTlsVersionsResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("tencentcloud:Waf/getTlsVersions:getTlsVersions", {
        "resultOutputFile": args.resultOutputFile,
    }, opts);
}

/**
 * A collection of arguments for invoking getTlsVersions.
 */
export interface GetTlsVersionsArgs {
    /**
     * Used to save results.
     */
    resultOutputFile?: string;
}

/**
 * A collection of values returned by getTlsVersions.
 */
export interface GetTlsVersionsResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly resultOutputFile?: string;
    /**
     * TLS key value.
     */
    readonly tls: outputs.Waf.GetTlsVersionsTl[];
}

export function getTlsVersionsOutput(args?: GetTlsVersionsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetTlsVersionsResult> {
    return pulumi.output(args).apply(a => getTlsVersions(a, opts))
}

/**
 * A collection of arguments for invoking getTlsVersions.
 */
export interface GetTlsVersionsOutputArgs {
    /**
     * Used to save results.
     */
    resultOutputFile?: pulumi.Input<string>;
}
