// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dlc

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/tencentcloudstack/pulumi-tencentcloud/sdk/go/tencentcloud/internal"
)

// Use this data source to query detailed information of DLC describe data engine image versions
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/tencentcloudstack/pulumi-tencentcloud/sdk/go/tencentcloud/dlc"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := dlc.GetDescribeDataEngineImageVersions(ctx, &dlc.GetDescribeDataEngineImageVersionsArgs{
//				EngineType: "SparkBatch",
//				Sort:       pulumi.StringRef("UpdateTime"),
//				Asc:        pulumi.BoolRef(false),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetDescribeDataEngineImageVersions(ctx *pulumi.Context, args *GetDescribeDataEngineImageVersionsArgs, opts ...pulumi.InvokeOption) (*GetDescribeDataEngineImageVersionsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetDescribeDataEngineImageVersionsResult
	err := ctx.Invoke("tencentcloud:Dlc/getDescribeDataEngineImageVersions:getDescribeDataEngineImageVersions", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDescribeDataEngineImageVersions.
type GetDescribeDataEngineImageVersionsArgs struct {
	// Sort by: false (descending, default), true (ascending).
	Asc *bool `pulumi:"asc"`
	// Engine type only support: SparkSQL/PrestoSQL/SparkBatch.
	EngineType string `pulumi:"engineType"`
	// Used to save results.
	ResultOutputFile *string `pulumi:"resultOutputFile"`
	// Sort fields: InsertTime (insert time, default), UpdateTime (update time).
	Sort *string `pulumi:"sort"`
}

// A collection of values returned by getDescribeDataEngineImageVersions.
type GetDescribeDataEngineImageVersionsResult struct {
	Asc *bool `pulumi:"asc"`
	// Cluster types: SparkSQL, PrestoSQL, and SparkBatch.
	EngineType string `pulumi:"engineType"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Major version of the image information list of clusters.
	ImageParentVersions []GetDescribeDataEngineImageVersionsImageParentVersion `pulumi:"imageParentVersions"`
	ResultOutputFile    *string                                                `pulumi:"resultOutputFile"`
	Sort                *string                                                `pulumi:"sort"`
}

func GetDescribeDataEngineImageVersionsOutput(ctx *pulumi.Context, args GetDescribeDataEngineImageVersionsOutputArgs, opts ...pulumi.InvokeOption) GetDescribeDataEngineImageVersionsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetDescribeDataEngineImageVersionsResultOutput, error) {
			args := v.(GetDescribeDataEngineImageVersionsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("tencentcloud:Dlc/getDescribeDataEngineImageVersions:getDescribeDataEngineImageVersions", args, GetDescribeDataEngineImageVersionsResultOutput{}, options).(GetDescribeDataEngineImageVersionsResultOutput), nil
		}).(GetDescribeDataEngineImageVersionsResultOutput)
}

// A collection of arguments for invoking getDescribeDataEngineImageVersions.
type GetDescribeDataEngineImageVersionsOutputArgs struct {
	// Sort by: false (descending, default), true (ascending).
	Asc pulumi.BoolPtrInput `pulumi:"asc"`
	// Engine type only support: SparkSQL/PrestoSQL/SparkBatch.
	EngineType pulumi.StringInput `pulumi:"engineType"`
	// Used to save results.
	ResultOutputFile pulumi.StringPtrInput `pulumi:"resultOutputFile"`
	// Sort fields: InsertTime (insert time, default), UpdateTime (update time).
	Sort pulumi.StringPtrInput `pulumi:"sort"`
}

func (GetDescribeDataEngineImageVersionsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDescribeDataEngineImageVersionsArgs)(nil)).Elem()
}

// A collection of values returned by getDescribeDataEngineImageVersions.
type GetDescribeDataEngineImageVersionsResultOutput struct{ *pulumi.OutputState }

func (GetDescribeDataEngineImageVersionsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDescribeDataEngineImageVersionsResult)(nil)).Elem()
}

func (o GetDescribeDataEngineImageVersionsResultOutput) ToGetDescribeDataEngineImageVersionsResultOutput() GetDescribeDataEngineImageVersionsResultOutput {
	return o
}

func (o GetDescribeDataEngineImageVersionsResultOutput) ToGetDescribeDataEngineImageVersionsResultOutputWithContext(ctx context.Context) GetDescribeDataEngineImageVersionsResultOutput {
	return o
}

func (o GetDescribeDataEngineImageVersionsResultOutput) Asc() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v GetDescribeDataEngineImageVersionsResult) *bool { return v.Asc }).(pulumi.BoolPtrOutput)
}

// Cluster types: SparkSQL, PrestoSQL, and SparkBatch.
func (o GetDescribeDataEngineImageVersionsResultOutput) EngineType() pulumi.StringOutput {
	return o.ApplyT(func(v GetDescribeDataEngineImageVersionsResult) string { return v.EngineType }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetDescribeDataEngineImageVersionsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetDescribeDataEngineImageVersionsResult) string { return v.Id }).(pulumi.StringOutput)
}

// Major version of the image information list of clusters.
func (o GetDescribeDataEngineImageVersionsResultOutput) ImageParentVersions() GetDescribeDataEngineImageVersionsImageParentVersionArrayOutput {
	return o.ApplyT(func(v GetDescribeDataEngineImageVersionsResult) []GetDescribeDataEngineImageVersionsImageParentVersion {
		return v.ImageParentVersions
	}).(GetDescribeDataEngineImageVersionsImageParentVersionArrayOutput)
}

func (o GetDescribeDataEngineImageVersionsResultOutput) ResultOutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetDescribeDataEngineImageVersionsResult) *string { return v.ResultOutputFile }).(pulumi.StringPtrOutput)
}

func (o GetDescribeDataEngineImageVersionsResultOutput) Sort() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetDescribeDataEngineImageVersionsResult) *string { return v.Sort }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDescribeDataEngineImageVersionsResultOutput{})
}
