// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Provides a resource to create a tem logConfig
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as tencentcloud from "@tencentcloud_iac/pulumi";
 *
 * const logConfig = new tencentcloud.tem.LogConfig("logConfig", {
 *     environmentId: "en-o5edaepv",
 *     applicationId: "app-3j29aa2p",
 *     workloadId: tencentcloudTemWorkload.workload.id,
 *     name: "terraform",
 *     logsetId: "b5824781-8d5b-4029-a2f7-d03c37f72bdf",
 *     topicId: "5a85bb6d-8e41-4e04-b7bd-c05e04782f94",
 *     inputType: "container_stdout",
 *     logType: "minimalist_log",
 * });
 * ```
 *
 * ## Import
 *
 * tem logConfig can be imported using the id, e.g.
 *
 * ```sh
 * $ pulumi import tencentcloud:Tem/logConfig:LogConfig logConfig environmentId#applicationId#name
 * ```
 */
export class LogConfig extends pulumi.CustomResource {
    /**
     * Get an existing LogConfig resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: LogConfigState, opts?: pulumi.CustomResourceOptions): LogConfig {
        return new LogConfig(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'tencentcloud:Tem/logConfig:LogConfig';

    /**
     * Returns true if the given object is an instance of LogConfig.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is LogConfig {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === LogConfig.__pulumiType;
    }

    /**
     * application ID.
     */
    declare public readonly applicationId: pulumi.Output<string>;
    /**
     * regex pattern.
     */
    declare public readonly beginningRegex: pulumi.Output<string | undefined>;
    /**
     * environment ID.
     */
    declare public readonly environmentId: pulumi.Output<string>;
    /**
     * file name pattern if container_file.
     */
    declare public readonly filePattern: pulumi.Output<string | undefined>;
    /**
     * container_stdout or container_file.
     */
    declare public readonly inputType: pulumi.Output<string>;
    /**
     * directory if container_file.
     */
    declare public readonly logPath: pulumi.Output<string | undefined>;
    /**
     * minimalist_log or multiline_log.
     */
    declare public readonly logType: pulumi.Output<string>;
    /**
     * logset.
     */
    declare public readonly logsetId: pulumi.Output<string>;
    /**
     * appConfig name.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * topic.
     */
    declare public readonly topicId: pulumi.Output<string>;
    /**
     * application ID, which is combined by environment ID and application ID, like `en-o5edaepv#app-3j29aa2p`.
     */
    declare public readonly workloadId: pulumi.Output<string>;

    /**
     * Create a LogConfig resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: LogConfigArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: LogConfigArgs | LogConfigState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as LogConfigState | undefined;
            resourceInputs["applicationId"] = state?.applicationId;
            resourceInputs["beginningRegex"] = state?.beginningRegex;
            resourceInputs["environmentId"] = state?.environmentId;
            resourceInputs["filePattern"] = state?.filePattern;
            resourceInputs["inputType"] = state?.inputType;
            resourceInputs["logPath"] = state?.logPath;
            resourceInputs["logType"] = state?.logType;
            resourceInputs["logsetId"] = state?.logsetId;
            resourceInputs["name"] = state?.name;
            resourceInputs["topicId"] = state?.topicId;
            resourceInputs["workloadId"] = state?.workloadId;
        } else {
            const args = argsOrState as LogConfigArgs | undefined;
            if (args?.applicationId === undefined && !opts.urn) {
                throw new Error("Missing required property 'applicationId'");
            }
            if (args?.environmentId === undefined && !opts.urn) {
                throw new Error("Missing required property 'environmentId'");
            }
            if (args?.inputType === undefined && !opts.urn) {
                throw new Error("Missing required property 'inputType'");
            }
            if (args?.logType === undefined && !opts.urn) {
                throw new Error("Missing required property 'logType'");
            }
            if (args?.logsetId === undefined && !opts.urn) {
                throw new Error("Missing required property 'logsetId'");
            }
            if (args?.topicId === undefined && !opts.urn) {
                throw new Error("Missing required property 'topicId'");
            }
            if (args?.workloadId === undefined && !opts.urn) {
                throw new Error("Missing required property 'workloadId'");
            }
            resourceInputs["applicationId"] = args?.applicationId;
            resourceInputs["beginningRegex"] = args?.beginningRegex;
            resourceInputs["environmentId"] = args?.environmentId;
            resourceInputs["filePattern"] = args?.filePattern;
            resourceInputs["inputType"] = args?.inputType;
            resourceInputs["logPath"] = args?.logPath;
            resourceInputs["logType"] = args?.logType;
            resourceInputs["logsetId"] = args?.logsetId;
            resourceInputs["name"] = args?.name;
            resourceInputs["topicId"] = args?.topicId;
            resourceInputs["workloadId"] = args?.workloadId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(LogConfig.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering LogConfig resources.
 */
export interface LogConfigState {
    /**
     * application ID.
     */
    applicationId?: pulumi.Input<string>;
    /**
     * regex pattern.
     */
    beginningRegex?: pulumi.Input<string>;
    /**
     * environment ID.
     */
    environmentId?: pulumi.Input<string>;
    /**
     * file name pattern if container_file.
     */
    filePattern?: pulumi.Input<string>;
    /**
     * container_stdout or container_file.
     */
    inputType?: pulumi.Input<string>;
    /**
     * directory if container_file.
     */
    logPath?: pulumi.Input<string>;
    /**
     * minimalist_log or multiline_log.
     */
    logType?: pulumi.Input<string>;
    /**
     * logset.
     */
    logsetId?: pulumi.Input<string>;
    /**
     * appConfig name.
     */
    name?: pulumi.Input<string>;
    /**
     * topic.
     */
    topicId?: pulumi.Input<string>;
    /**
     * application ID, which is combined by environment ID and application ID, like `en-o5edaepv#app-3j29aa2p`.
     */
    workloadId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a LogConfig resource.
 */
export interface LogConfigArgs {
    /**
     * application ID.
     */
    applicationId: pulumi.Input<string>;
    /**
     * regex pattern.
     */
    beginningRegex?: pulumi.Input<string>;
    /**
     * environment ID.
     */
    environmentId: pulumi.Input<string>;
    /**
     * file name pattern if container_file.
     */
    filePattern?: pulumi.Input<string>;
    /**
     * container_stdout or container_file.
     */
    inputType: pulumi.Input<string>;
    /**
     * directory if container_file.
     */
    logPath?: pulumi.Input<string>;
    /**
     * minimalist_log or multiline_log.
     */
    logType: pulumi.Input<string>;
    /**
     * logset.
     */
    logsetId: pulumi.Input<string>;
    /**
     * appConfig name.
     */
    name?: pulumi.Input<string>;
    /**
     * topic.
     */
    topicId: pulumi.Input<string>;
    /**
     * application ID, which is combined by environment ID and application ID, like `en-o5edaepv#app-3j29aa2p`.
     */
    workloadId: pulumi.Input<string>;
}
