// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace TencentCloudIAC.PulumiPackage.Tencentcloud.Antiddos.Outputs
{

    [OutputType]
    public sealed class GetBgpInstancesBgpInstanceListStandardPackageConfigResult
    {
        /// <summary>
        /// Protection bandwidth 50Mbps.
        /// </summary>
        public readonly int Bandwidth;
        /// <summary>
        /// Whether to enable elastic business bandwidth.
        /// true: enable
        /// false: disable
        /// Default is disable.
        /// </summary>
        public readonly bool ElasticBandwidthFlag;
        /// <summary>
        /// Number of protected IPs.
        /// </summary>
        public readonly int ProtectIpCount;
        /// <summary>
        /// Region where the Anti-DDoS package is purchased.
        /// </summary>
        public readonly string Region;

        [OutputConstructor]
        private GetBgpInstancesBgpInstanceListStandardPackageConfigResult(
            int bandwidth,

            bool elasticBandwidthFlag,

            int protectIpCount,

            string region)
        {
            Bandwidth = bandwidth;
            ElasticBandwidthFlag = elasticBandwidthFlag;
            ProtectIpCount = protectIpCount;
            Region = region;
        }
    }
}
