# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import sys
from collections.abc import Mapping, Sequence
from typing import Union, overload

import pulumi
import pulumi.runtime

if sys.version_info >= (3, 11):
    pass
else:
    pass
from .. import _utilities
from . import outputs
from ._inputs import *

__all__ = ["ServerlessNodePool", "ServerlessNodePoolArgs"]


@pulumi.input_type
class ServerlessNodePoolArgs:
    def __init__(
        __self__,
        *,
        cluster_id: pulumi.Input[_builtins.str],
        serverless_nodes: pulumi.Input[
            Sequence[pulumi.Input["ServerlessNodePoolServerlessNodeArgs"]]
        ],
        labels: pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]] | None] = None,
        name: pulumi.Input[_builtins.str | None] = None,
        security_group_ids: pulumi.Input[
            Sequence[pulumi.Input[_builtins.str]] | None
        ] = None,
        taints: pulumi.Input[
            Sequence[pulumi.Input["ServerlessNodePoolTaintArgs"]] | None
        ] = None
    ):
        """
        The set of arguments for constructing a ServerlessNodePool resource.

        :param pulumi.Input[_builtins.str] cluster_id: cluster id of serverless node pool.
        :param pulumi.Input[Sequence[pulumi.Input['ServerlessNodePoolServerlessNodeArgs']]] serverless_nodes: node list of serverless node pool.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: labels of serverless node.
        :param pulumi.Input[_builtins.str] name: serverless node pool name.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] security_group_ids: security groups of serverless node pool.
        :param pulumi.Input[Sequence[pulumi.Input['ServerlessNodePoolTaintArgs']]] taints: taints of serverless node.
        """
        pulumi.set(__self__, "cluster_id", cluster_id)
        pulumi.set(__self__, "serverless_nodes", serverless_nodes)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if security_group_ids is not None:
            pulumi.set(__self__, "security_group_ids", security_group_ids)
        if taints is not None:
            pulumi.set(__self__, "taints", taints)

    @_builtins.property
    @pulumi.getter(name="clusterId")
    def cluster_id(self) -> pulumi.Input[_builtins.str]:
        """
        cluster id of serverless node pool.
        """
        return pulumi.get(self, "cluster_id")

    @cluster_id.setter
    def cluster_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "cluster_id", value)

    @_builtins.property
    @pulumi.getter(name="serverlessNodes")
    def serverless_nodes(
        self,
    ) -> pulumi.Input[Sequence[pulumi.Input["ServerlessNodePoolServerlessNodeArgs"]]]:
        """
        node list of serverless node pool.
        """
        return pulumi.get(self, "serverless_nodes")

    @serverless_nodes.setter
    def serverless_nodes(
        self,
        value: pulumi.Input[
            Sequence[pulumi.Input["ServerlessNodePoolServerlessNodeArgs"]]
        ],
    ):
        pulumi.set(self, "serverless_nodes", value)

    @_builtins.property
    @pulumi.getter
    def labels(
        self,
    ) -> pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]] | None]:
        """
        labels of serverless node.
        """
        return pulumi.get(self, "labels")

    @labels.setter
    def labels(
        self, value: pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]] | None]
    ):
        pulumi.set(self, "labels", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str | None]:
        """
        serverless node pool name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="securityGroupIds")
    def security_group_ids(
        self,
    ) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]] | None]:
        """
        security groups of serverless node pool.
        """
        return pulumi.get(self, "security_group_ids")

    @security_group_ids.setter
    def security_group_ids(
        self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]] | None]
    ):
        pulumi.set(self, "security_group_ids", value)

    @_builtins.property
    @pulumi.getter
    def taints(
        self,
    ) -> pulumi.Input[Sequence[pulumi.Input["ServerlessNodePoolTaintArgs"]] | None]:
        """
        taints of serverless node.
        """
        return pulumi.get(self, "taints")

    @taints.setter
    def taints(
        self,
        value: pulumi.Input[
            Sequence[pulumi.Input["ServerlessNodePoolTaintArgs"]] | None
        ],
    ):
        pulumi.set(self, "taints", value)


@pulumi.input_type
class _ServerlessNodePoolState:
    def __init__(
        __self__,
        *,
        cluster_id: pulumi.Input[_builtins.str | None] = None,
        labels: pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]] | None] = None,
        life_state: pulumi.Input[_builtins.str | None] = None,
        name: pulumi.Input[_builtins.str | None] = None,
        security_group_ids: pulumi.Input[
            Sequence[pulumi.Input[_builtins.str]] | None
        ] = None,
        serverless_nodes: pulumi.Input[
            Sequence[pulumi.Input["ServerlessNodePoolServerlessNodeArgs"]] | None
        ] = None,
        taints: pulumi.Input[
            Sequence[pulumi.Input["ServerlessNodePoolTaintArgs"]] | None
        ] = None
    ):
        """
        Input properties used for looking up and filtering ServerlessNodePool resources.

        :param pulumi.Input[_builtins.str] cluster_id: cluster id of serverless node pool.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: labels of serverless node.
        :param pulumi.Input[_builtins.str] life_state: life state of serverless node pool.
        :param pulumi.Input[_builtins.str] name: serverless node pool name.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] security_group_ids: security groups of serverless node pool.
        :param pulumi.Input[Sequence[pulumi.Input['ServerlessNodePoolServerlessNodeArgs']]] serverless_nodes: node list of serverless node pool.
        :param pulumi.Input[Sequence[pulumi.Input['ServerlessNodePoolTaintArgs']]] taints: taints of serverless node.
        """
        if cluster_id is not None:
            pulumi.set(__self__, "cluster_id", cluster_id)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)
        if life_state is not None:
            pulumi.set(__self__, "life_state", life_state)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if security_group_ids is not None:
            pulumi.set(__self__, "security_group_ids", security_group_ids)
        if serverless_nodes is not None:
            pulumi.set(__self__, "serverless_nodes", serverless_nodes)
        if taints is not None:
            pulumi.set(__self__, "taints", taints)

    @_builtins.property
    @pulumi.getter(name="clusterId")
    def cluster_id(self) -> pulumi.Input[_builtins.str | None]:
        """
        cluster id of serverless node pool.
        """
        return pulumi.get(self, "cluster_id")

    @cluster_id.setter
    def cluster_id(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "cluster_id", value)

    @_builtins.property
    @pulumi.getter
    def labels(
        self,
    ) -> pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]] | None]:
        """
        labels of serverless node.
        """
        return pulumi.get(self, "labels")

    @labels.setter
    def labels(
        self, value: pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]] | None]
    ):
        pulumi.set(self, "labels", value)

    @_builtins.property
    @pulumi.getter(name="lifeState")
    def life_state(self) -> pulumi.Input[_builtins.str | None]:
        """
        life state of serverless node pool.
        """
        return pulumi.get(self, "life_state")

    @life_state.setter
    def life_state(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "life_state", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str | None]:
        """
        serverless node pool name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="securityGroupIds")
    def security_group_ids(
        self,
    ) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]] | None]:
        """
        security groups of serverless node pool.
        """
        return pulumi.get(self, "security_group_ids")

    @security_group_ids.setter
    def security_group_ids(
        self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]] | None]
    ):
        pulumi.set(self, "security_group_ids", value)

    @_builtins.property
    @pulumi.getter(name="serverlessNodes")
    def serverless_nodes(
        self,
    ) -> pulumi.Input[
        Sequence[pulumi.Input["ServerlessNodePoolServerlessNodeArgs"]] | None
    ]:
        """
        node list of serverless node pool.
        """
        return pulumi.get(self, "serverless_nodes")

    @serverless_nodes.setter
    def serverless_nodes(
        self,
        value: pulumi.Input[
            Sequence[pulumi.Input["ServerlessNodePoolServerlessNodeArgs"]] | None
        ],
    ):
        pulumi.set(self, "serverless_nodes", value)

    @_builtins.property
    @pulumi.getter
    def taints(
        self,
    ) -> pulumi.Input[Sequence[pulumi.Input["ServerlessNodePoolTaintArgs"]] | None]:
        """
        taints of serverless node.
        """
        return pulumi.get(self, "taints")

    @taints.setter
    def taints(
        self,
        value: pulumi.Input[
            Sequence[pulumi.Input["ServerlessNodePoolTaintArgs"]] | None
        ],
    ):
        pulumi.set(self, "taints", value)


@pulumi.type_token("tencentcloud:Kubernetes/serverlessNodePool:ServerlessNodePool")
class ServerlessNodePool(pulumi.CustomResource):
    @overload
    def __init__(
        __self__,
        resource_name: str,
        opts: pulumi.ResourceOptions | None = None,
        cluster_id: pulumi.Input[_builtins.str | None] = None,
        labels: pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]] | None] = None,
        name: pulumi.Input[_builtins.str | None] = None,
        security_group_ids: pulumi.Input[
            Sequence[pulumi.Input[_builtins.str]] | None
        ] = None,
        serverless_nodes: pulumi.Input[
            Sequence[
                pulumi.Input[
                    Union[
                        "ServerlessNodePoolServerlessNodeArgs",
                        "ServerlessNodePoolServerlessNodeArgsDict",
                    ]
                ]
            ]
            | None
        ] = None,
        taints: pulumi.Input[
            Sequence[
                pulumi.Input[
                    Union[
                        "ServerlessNodePoolTaintArgs", "ServerlessNodePoolTaintArgsDict"
                    ]
                ]
            ]
            | None
        ] = None,
        __props__=None,
    ):
        """
        Provide a resource to create serverless node pool of cluster.

        ## Example Usage

        ### Add serverless node pool to a cluster

        ```python
        import pulumi
        import pulumi_tencentcloud as tencentcloud
        import tencentcloud_iac_pulumi as tencentcloud

        config = pulumi.Config()
        availability_zone = config.get("availabilityZone")
        if availability_zone is None:
            availability_zone = "ap-guangzhou-3"
        example_cluster_cidr = config.get("exampleClusterCidr")
        if example_cluster_cidr is None:
            example_cluster_cidr = "10.31.0.0/16"
        vpc = tencentcloud.vpc.get_subnets(is_default=True,
            availability_zone=availability_zone)
        vpc_id = vpc.instance_lists[0].vpc_id
        subnet_id = vpc.instance_lists[0].subnet_id
        sg = tencentcloud.security.get_groups(name="default")
        sg_id = sg.security_groups[0].security_group_id
        example = tencentcloud.kubernetes.Cluster("example",
            vpc_id=vpc_id,
            cluster_cidr=example_cluster_cidr,
            cluster_max_pod_num=32,
            cluster_name="tf_example_cluster",
            cluster_desc="tf example cluster",
            cluster_max_service_num=32,
            cluster_version="1.18.4",
            cluster_deploy_type="MANAGED_CLUSTER")
        example_serverless_node_pool = tencentcloud.kubernetes.ServerlessNodePool("example",
            cluster_id=example.id,
            name="tf_example_serverless_node_pool",
            serverless_nodes=[
                {
                    "display_name": "tf_example_serverless_node1",
                    "subnet_id": subnet_id,
                },
                {
                    "display_name": "tf_example_serverless_node2",
                    "subnet_id": subnet_id,
                },
            ],
            security_group_ids=[sg_id],
            labels={
                "label1": "value1",
                "label2": "value2",
            })
        ```

        ### Adding taints to the virtual nodes under this node pool

        The pods without appropriate tolerations will not be scheduled on this node. Refer [taint-and-toleration](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) for more details.

        ```python
        import pulumi
        import tencentcloud_iac_pulumi as tencentcloud

        example = tencentcloud.kubernetes.ServerlessNodePool("example",
            cluster_id=example_tencentcloud_kubernetes_cluster["id"],
            name="tf_example_serverless_node_pool",
            serverless_nodes=[
                {
                    "display_name": "tf_example_serverless_node1",
                    "subnet_id": subnet_id,
                },
                {
                    "display_name": "tf_example_serverless_node2",
                    "subnet_id": subnet_id,
                },
            ],
            security_group_ids=[sg_id],
            labels={
                "label1": "value1",
                "label2": "value2",
            },
            taints=[
                {
                    "key": "key1",
                    "value": "value1",
                    "effect": "NoSchedule",
                },
                {
                    "key": "key1",
                    "value": "value1",
                    "effect": "NoExecute",
                },
            ])
        ```

        ## Import

        serverless node pool can be imported using the clusterId#nodePoolId, e.g.

        ```sh
        $ pulumi import tencentcloud:Kubernetes/serverlessNodePool:ServerlessNodePool example cls-62ch3v24#np-5avod190
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] cluster_id: cluster id of serverless node pool.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: labels of serverless node.
        :param pulumi.Input[_builtins.str] name: serverless node pool name.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] security_group_ids: security groups of serverless node pool.
        :param pulumi.Input[Sequence[pulumi.Input[Union['ServerlessNodePoolServerlessNodeArgs', 'ServerlessNodePoolServerlessNodeArgsDict']]]] serverless_nodes: node list of serverless node pool.
        :param pulumi.Input[Sequence[pulumi.Input[Union['ServerlessNodePoolTaintArgs', 'ServerlessNodePoolTaintArgsDict']]]] taints: taints of serverless node.
        """

    @overload
    def __init__(
        __self__,
        resource_name: str,
        args: ServerlessNodePoolArgs,
        opts: pulumi.ResourceOptions | None = None,
    ):
        """
        Provide a resource to create serverless node pool of cluster.

        ## Example Usage

        ### Add serverless node pool to a cluster

        ```python
        import pulumi
        import pulumi_tencentcloud as tencentcloud
        import tencentcloud_iac_pulumi as tencentcloud

        config = pulumi.Config()
        availability_zone = config.get("availabilityZone")
        if availability_zone is None:
            availability_zone = "ap-guangzhou-3"
        example_cluster_cidr = config.get("exampleClusterCidr")
        if example_cluster_cidr is None:
            example_cluster_cidr = "10.31.0.0/16"
        vpc = tencentcloud.vpc.get_subnets(is_default=True,
            availability_zone=availability_zone)
        vpc_id = vpc.instance_lists[0].vpc_id
        subnet_id = vpc.instance_lists[0].subnet_id
        sg = tencentcloud.security.get_groups(name="default")
        sg_id = sg.security_groups[0].security_group_id
        example = tencentcloud.kubernetes.Cluster("example",
            vpc_id=vpc_id,
            cluster_cidr=example_cluster_cidr,
            cluster_max_pod_num=32,
            cluster_name="tf_example_cluster",
            cluster_desc="tf example cluster",
            cluster_max_service_num=32,
            cluster_version="1.18.4",
            cluster_deploy_type="MANAGED_CLUSTER")
        example_serverless_node_pool = tencentcloud.kubernetes.ServerlessNodePool("example",
            cluster_id=example.id,
            name="tf_example_serverless_node_pool",
            serverless_nodes=[
                {
                    "display_name": "tf_example_serverless_node1",
                    "subnet_id": subnet_id,
                },
                {
                    "display_name": "tf_example_serverless_node2",
                    "subnet_id": subnet_id,
                },
            ],
            security_group_ids=[sg_id],
            labels={
                "label1": "value1",
                "label2": "value2",
            })
        ```

        ### Adding taints to the virtual nodes under this node pool

        The pods without appropriate tolerations will not be scheduled on this node. Refer [taint-and-toleration](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) for more details.

        ```python
        import pulumi
        import tencentcloud_iac_pulumi as tencentcloud

        example = tencentcloud.kubernetes.ServerlessNodePool("example",
            cluster_id=example_tencentcloud_kubernetes_cluster["id"],
            name="tf_example_serverless_node_pool",
            serverless_nodes=[
                {
                    "display_name": "tf_example_serverless_node1",
                    "subnet_id": subnet_id,
                },
                {
                    "display_name": "tf_example_serverless_node2",
                    "subnet_id": subnet_id,
                },
            ],
            security_group_ids=[sg_id],
            labels={
                "label1": "value1",
                "label2": "value2",
            },
            taints=[
                {
                    "key": "key1",
                    "value": "value1",
                    "effect": "NoSchedule",
                },
                {
                    "key": "key1",
                    "value": "value1",
                    "effect": "NoExecute",
                },
            ])
        ```

        ## Import

        serverless node pool can be imported using the clusterId#nodePoolId, e.g.

        ```sh
        $ pulumi import tencentcloud:Kubernetes/serverlessNodePool:ServerlessNodePool example cls-62ch3v24#np-5avod190
        ```


        :param str resource_name: The name of the resource.
        :param ServerlessNodePoolArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """

    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(
            ServerlessNodePoolArgs, pulumi.ResourceOptions, *args, **kwargs
        )
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(
        __self__,
        resource_name: str,
        opts: pulumi.ResourceOptions | None = None,
        cluster_id: pulumi.Input[_builtins.str | None] = None,
        labels: pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]] | None] = None,
        name: pulumi.Input[_builtins.str | None] = None,
        security_group_ids: pulumi.Input[
            Sequence[pulumi.Input[_builtins.str]] | None
        ] = None,
        serverless_nodes: pulumi.Input[
            Sequence[
                pulumi.Input[
                    Union[
                        "ServerlessNodePoolServerlessNodeArgs",
                        "ServerlessNodePoolServerlessNodeArgsDict",
                    ]
                ]
            ]
            | None
        ] = None,
        taints: pulumi.Input[
            Sequence[
                pulumi.Input[
                    Union[
                        "ServerlessNodePoolTaintArgs", "ServerlessNodePoolTaintArgsDict"
                    ]
                ]
            ]
            | None
        ] = None,
        __props__=None,
    ):
        opts = pulumi.ResourceOptions.merge(
            _utilities.get_resource_opts_defaults(), opts
        )
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError(
                "Expected resource options to be a ResourceOptions instance"
            )
        if opts.id is None:
            if __props__ is not None:
                raise TypeError(
                    "__props__ is only valid when passed in combination with a valid opts.id to get an existing resource"
                )
            __props__ = ServerlessNodePoolArgs.__new__(ServerlessNodePoolArgs)

            if cluster_id is None and not opts.urn:
                raise TypeError("Missing required property 'cluster_id'")
            __props__.__dict__["cluster_id"] = cluster_id
            __props__.__dict__["labels"] = labels
            __props__.__dict__["name"] = name
            __props__.__dict__["security_group_ids"] = security_group_ids
            if serverless_nodes is None and not opts.urn:
                raise TypeError("Missing required property 'serverless_nodes'")
            __props__.__dict__["serverless_nodes"] = serverless_nodes
            __props__.__dict__["taints"] = taints
            __props__.__dict__["life_state"] = None
        super().__init__(
            "tencentcloud:Kubernetes/serverlessNodePool:ServerlessNodePool",
            resource_name,
            __props__,
            opts,
        )

    @staticmethod
    def get(
        resource_name: str,
        id: pulumi.Input[str],
        opts: pulumi.ResourceOptions | None = None,
        cluster_id: pulumi.Input[_builtins.str | None] = None,
        labels: pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]] | None] = None,
        life_state: pulumi.Input[_builtins.str | None] = None,
        name: pulumi.Input[_builtins.str | None] = None,
        security_group_ids: pulumi.Input[
            Sequence[pulumi.Input[_builtins.str]] | None
        ] = None,
        serverless_nodes: pulumi.Input[
            Sequence[
                pulumi.Input[
                    Union[
                        "ServerlessNodePoolServerlessNodeArgs",
                        "ServerlessNodePoolServerlessNodeArgsDict",
                    ]
                ]
            ]
            | None
        ] = None,
        taints: pulumi.Input[
            Sequence[
                pulumi.Input[
                    Union[
                        "ServerlessNodePoolTaintArgs", "ServerlessNodePoolTaintArgsDict"
                    ]
                ]
            ]
            | None
        ] = None,
    ) -> "ServerlessNodePool":
        """
        Get an existing ServerlessNodePool resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] cluster_id: cluster id of serverless node pool.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: labels of serverless node.
        :param pulumi.Input[_builtins.str] life_state: life state of serverless node pool.
        :param pulumi.Input[_builtins.str] name: serverless node pool name.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] security_group_ids: security groups of serverless node pool.
        :param pulumi.Input[Sequence[pulumi.Input[Union['ServerlessNodePoolServerlessNodeArgs', 'ServerlessNodePoolServerlessNodeArgsDict']]]] serverless_nodes: node list of serverless node pool.
        :param pulumi.Input[Sequence[pulumi.Input[Union['ServerlessNodePoolTaintArgs', 'ServerlessNodePoolTaintArgsDict']]]] taints: taints of serverless node.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ServerlessNodePoolState.__new__(_ServerlessNodePoolState)

        __props__.__dict__["cluster_id"] = cluster_id
        __props__.__dict__["labels"] = labels
        __props__.__dict__["life_state"] = life_state
        __props__.__dict__["name"] = name
        __props__.__dict__["security_group_ids"] = security_group_ids
        __props__.__dict__["serverless_nodes"] = serverless_nodes
        __props__.__dict__["taints"] = taints
        return ServerlessNodePool(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="clusterId")
    def cluster_id(self) -> pulumi.Output[_builtins.str]:
        """
        cluster id of serverless node pool.
        """
        return pulumi.get(self, "cluster_id")

    @_builtins.property
    @pulumi.getter
    def labels(self) -> pulumi.Output[Mapping[str, _builtins.str] | None]:
        """
        labels of serverless node.
        """
        return pulumi.get(self, "labels")

    @_builtins.property
    @pulumi.getter(name="lifeState")
    def life_state(self) -> pulumi.Output[_builtins.str]:
        """
        life state of serverless node pool.
        """
        return pulumi.get(self, "life_state")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        serverless node pool name.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="securityGroupIds")
    def security_group_ids(self) -> pulumi.Output[Sequence[_builtins.str] | None]:
        """
        security groups of serverless node pool.
        """
        return pulumi.get(self, "security_group_ids")

    @_builtins.property
    @pulumi.getter(name="serverlessNodes")
    def serverless_nodes(
        self,
    ) -> pulumi.Output[Sequence["outputs.ServerlessNodePoolServerlessNode"]]:
        """
        node list of serverless node pool.
        """
        return pulumi.get(self, "serverless_nodes")

    @_builtins.property
    @pulumi.getter
    def taints(
        self,
    ) -> pulumi.Output[Sequence["outputs.ServerlessNodePoolTaint"] | None]:
        """
        taints of serverless node.
        """
        return pulumi.get(self, "taints")
