// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace TencentCloudIAC.PulumiPackage.Tencentcloud.Oceanus.Inputs
{

    public sealed class JobConfigResourceRefArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Resource ID.
        /// </summary>
        [Input("resourceId", required: true)]
        public Input<string> ResourceId { get; set; } = null!;

        /// <summary>
        /// Reference resource type, for example, setting the main resource to 1 represents the jar package where the main class is located.
        /// </summary>
        [Input("type", required: true)]
        public Input<int> Type { get; set; } = null!;

        /// <summary>
        /// Resource version ID, -1 indicates the latest version.
        /// </summary>
        [Input("version", required: true)]
        public Input<int> Version { get; set; } = null!;

        public JobConfigResourceRefArgs()
        {
        }
        public static new JobConfigResourceRefArgs Empty => new JobConfigResourceRefArgs();
    }
}
