// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace TencentCloudIAC.PulumiPackage.Tencentcloud.Cdwpg
{
    /// <summary>
    /// Provides a resource to create a cdwpg CdwpgUserhba
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Tencentcloud = TencentCloudIAC.PulumiPackage.Tencentcloud;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var cdwpgUserhba = new Tencentcloud.Cdwpg.Userhba("cdwpg_userhba", new()
    ///     {
    ///         InstanceId = "cdwpg-zpiemnyd",
    ///         HbaConfigs = new[]
    ///         {
    ///             new Tencentcloud.Cdwpg.Inputs.UserhbaHbaConfigArgs
    ///             {
    ///                 Type = "host",
    ///                 Database = "all",
    ///                 User = "all",
    ///                 Address = "0.0.0.0/0",
    ///                 Method = "md5",
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// cdwpg cdwpg_userhba can be imported using the id, e.g.
    /// 
    /// ```sh
    /// $ pulumi import tencentcloud:Cdwpg/userhba:Userhba cdwpg_userhba cdwpg_userhba_id
    /// ```
    /// </summary>
    [TencentcloudResourceType("tencentcloud:Cdwpg/userhba:Userhba")]
    public partial class Userhba : global::Pulumi.CustomResource
    {
        /// <summary>
        /// HBA configuration array.
        /// </summary>
        [Output("hbaConfigs")]
        public Output<ImmutableArray<Outputs.UserhbaHbaConfig>> HbaConfigs { get; private set; } = null!;

        /// <summary>
        /// Instance id.
        /// </summary>
        [Output("instanceId")]
        public Output<string> InstanceId { get; private set; } = null!;


        /// <summary>
        /// Create a Userhba resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Userhba(string name, UserhbaArgs args, CustomResourceOptions? options = null)
            : base("tencentcloud:Cdwpg/userhba:Userhba", name, args ?? new UserhbaArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Userhba(string name, Input<string> id, UserhbaState? state = null, CustomResourceOptions? options = null)
            : base("tencentcloud:Cdwpg/userhba:Userhba", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/tencentcloudstack",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Userhba resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Userhba Get(string name, Input<string> id, UserhbaState? state = null, CustomResourceOptions? options = null)
        {
            return new Userhba(name, id, state, options);
        }
    }

    public sealed class UserhbaArgs : global::Pulumi.ResourceArgs
    {
        [Input("hbaConfigs")]
        private InputList<Inputs.UserhbaHbaConfigArgs>? _hbaConfigs;

        /// <summary>
        /// HBA configuration array.
        /// </summary>
        public InputList<Inputs.UserhbaHbaConfigArgs> HbaConfigs
        {
            get => _hbaConfigs ?? (_hbaConfigs = new InputList<Inputs.UserhbaHbaConfigArgs>());
            set => _hbaConfigs = value;
        }

        /// <summary>
        /// Instance id.
        /// </summary>
        [Input("instanceId", required: true)]
        public Input<string> InstanceId { get; set; } = null!;

        public UserhbaArgs()
        {
        }
        public static new UserhbaArgs Empty => new UserhbaArgs();
    }

    public sealed class UserhbaState : global::Pulumi.ResourceArgs
    {
        [Input("hbaConfigs")]
        private InputList<Inputs.UserhbaHbaConfigGetArgs>? _hbaConfigs;

        /// <summary>
        /// HBA configuration array.
        /// </summary>
        public InputList<Inputs.UserhbaHbaConfigGetArgs> HbaConfigs
        {
            get => _hbaConfigs ?? (_hbaConfigs = new InputList<Inputs.UserhbaHbaConfigGetArgs>());
            set => _hbaConfigs = value;
        }

        /// <summary>
        /// Instance id.
        /// </summary>
        [Input("instanceId")]
        public Input<string>? InstanceId { get; set; }

        public UserhbaState()
        {
        }
        public static new UserhbaState Empty => new UserhbaState();
    }
}
