// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Provides a resource to create a vpc normalAddressReturn
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as tencentcloud from "@tencentcloud_iac/pulumi";
 *
 * const example = new tencentcloud.eip.NormalAddressReturn("example", {addressIps: ["172.16.17.32"]});
 * ```
 */
export class NormalAddressReturn extends pulumi.CustomResource {
    /**
     * Get an existing NormalAddressReturn resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NormalAddressReturnState, opts?: pulumi.CustomResourceOptions): NormalAddressReturn {
        return new NormalAddressReturn(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'tencentcloud:Eip/normalAddressReturn:NormalAddressReturn';

    /**
     * Returns true if the given object is an instance of NormalAddressReturn.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NormalAddressReturn {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NormalAddressReturn.__pulumiType;
    }

    /**
     * The IP address of the EIP, example: 101.35.139.183.
     */
    declare public readonly addressIps: pulumi.Output<string[] | undefined>;

    /**
     * Create a NormalAddressReturn resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: NormalAddressReturnArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NormalAddressReturnArgs | NormalAddressReturnState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as NormalAddressReturnState | undefined;
            resourceInputs["addressIps"] = state?.addressIps;
        } else {
            const args = argsOrState as NormalAddressReturnArgs | undefined;
            resourceInputs["addressIps"] = args?.addressIps;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(NormalAddressReturn.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering NormalAddressReturn resources.
 */
export interface NormalAddressReturnState {
    /**
     * The IP address of the EIP, example: 101.35.139.183.
     */
    addressIps?: pulumi.Input<pulumi.Input<string>[]>;
}

/**
 * The set of arguments for constructing a NormalAddressReturn resource.
 */
export interface NormalAddressReturnArgs {
    /**
     * The IP address of the EIP, example: 101.35.139.183.
     */
    addressIps?: pulumi.Input<pulumi.Input<string>[]>;
}
