// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace TencentCloudIAC.PulumiPackage.Tencentcloud.Gaap.Outputs
{

    [OutputType]
    public sealed class GetLayer7ListenersListenerResult
    {
        /// <summary>
        /// Authentication type of the layer7 listener. `0` is one-way authentication and `1` is mutual authentication.
        /// </summary>
        public readonly int AuthType;
        /// <summary>
        /// Certificate ID of the layer7 listener.
        /// </summary>
        public readonly string CertificateId;
        /// <summary>
        /// (**Deprecated**) It has been deprecated from version 1.26.0. Use `client_certificate_ids` instead. ID of the client certificate.
        /// </summary>
        public readonly string ClientCertificateId;
        /// <summary>
        /// ID list of the client certificate.
        /// </summary>
        public readonly ImmutableArray<string> ClientCertificateIds;
        /// <summary>
        /// Creation time of the layer7 listener.
        /// </summary>
        public readonly string CreateTime;
        /// <summary>
        /// Protocol type of the forwarding.
        /// </summary>
        public readonly string ForwardProtocol;
        /// <summary>
        /// ID of the layer7 listener.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Name of the layer7 listener.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Port of the layer7 listener to be queried.
        /// </summary>
        public readonly int Port;
        /// <summary>
        /// Protocol of the layer7 listener to be queried. Valid values: `HTTP` and `HTTPS`.
        /// </summary>
        public readonly string Protocol;
        /// <summary>
        /// ID of the GAAP proxy to be queried.
        /// </summary>
        public readonly string ProxyId;
        /// <summary>
        /// Status of the layer7 listener.
        /// </summary>
        public readonly int Status;
        /// <summary>
        /// Password Suite, optional GAAP_TLS_CIPHERS_STRICT, GAAP_TLS_CIPHERS_GENERAL, GAAP_TLS_CIPHERS_WIDE(default).
        /// </summary>
        public readonly string TlsCiphers;
        /// <summary>
        /// TLS version, optional TLSv1, TLSv1.1, TLSv1.2, TLSv1.3.
        /// </summary>
        public readonly ImmutableArray<string> TlsSupportVersions;

        [OutputConstructor]
        private GetLayer7ListenersListenerResult(
            int authType,

            string certificateId,

            string clientCertificateId,

            ImmutableArray<string> clientCertificateIds,

            string createTime,

            string forwardProtocol,

            string id,

            string name,

            int port,

            string protocol,

            string proxyId,

            int status,

            string tlsCiphers,

            ImmutableArray<string> tlsSupportVersions)
        {
            AuthType = authType;
            CertificateId = certificateId;
            ClientCertificateId = clientCertificateId;
            ClientCertificateIds = clientCertificateIds;
            CreateTime = createTime;
            ForwardProtocol = forwardProtocol;
            Id = id;
            Name = name;
            Port = port;
            Protocol = protocol;
            ProxyId = proxyId;
            Status = status;
            TlsCiphers = tlsCiphers;
            TlsSupportVersions = tlsSupportVersions;
        }
    }
}
