// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace TencentCloudIAC.PulumiPackage.Tencentcloud.Teo
{
    /// <summary>
    /// Provides a resource to manage TEO edge function component binding configuration
    /// 
    /// &gt; **NOTE:** If this resource management method is used, it must be the sole method employed; management via other channels—such as the console, API, or CLI—is prohibited. Doing so would result in unintended changes or cause `Apply` or `Destroy` operations to overwrite existing configurations.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Tencentcloud = TencentCloudIAC.PulumiPackage.Tencentcloud;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Tencentcloud.Teo.FunctionComponentBinding("example", new()
    ///     {
    ///         ZoneId = "zone-2qtuhspy7cr6",
    ///         FunctionId = "ef-txx7fnua",
    ///         FunctionComponentBindings = new[]
    ///         {
    ///             new Tencentcloud.Teo.Inputs.FunctionComponentBindingFunctionComponentBindingArgs
    ///             {
    ///                 Type = "kv_namespace",
    ///                 VariableName = "MY_KV",
    ///                 KvNamespaceParameters = new Tencentcloud.Teo.Inputs.FunctionComponentBindingFunctionComponentBindingKvNamespaceParametersArgs
    ///                 {
    ///                     ZoneId = "zone-2qtuhspy7cr6",
    ///                     Namespace = "my-namespace",
    ///                 },
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// teo FunctionComponentBinding can be imported using the composite id (zone_id#function_id), e.g.
    /// 
    /// ```sh
    /// $ pulumi import tencentcloud:Teo/functionComponentBinding:FunctionComponentBinding example zone-2qtuhspy7cr6#ef-txx7fnua
    /// ```
    /// </summary>
    [TencentcloudResourceType("tencentcloud:Teo/functionComponentBinding:FunctionComponentBinding")]
    public partial class FunctionComponentBinding : global::Pulumi.CustomResource
    {
        /// <summary>
        /// List of function component bindings.
        /// </summary>
        [Output("functionComponentBindings")]
        public Output<ImmutableArray<Outputs.FunctionComponentBindingFunctionComponentBinding>> FunctionComponentBindings { get; private set; } = null!;

        /// <summary>
        /// Function ID.
        /// </summary>
        [Output("functionId")]
        public Output<string> FunctionId { get; private set; } = null!;

        /// <summary>
        /// Site ID.
        /// </summary>
        [Output("zoneId")]
        public Output<string> ZoneId { get; private set; } = null!;


        /// <summary>
        /// Create a FunctionComponentBinding resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public FunctionComponentBinding(string name, FunctionComponentBindingArgs args, CustomResourceOptions? options = null)
            : base("tencentcloud:Teo/functionComponentBinding:FunctionComponentBinding", name, args ?? new FunctionComponentBindingArgs(), MakeResourceOptions(options, ""))
        {
        }

        private FunctionComponentBinding(string name, Input<string> id, FunctionComponentBindingState? state = null, CustomResourceOptions? options = null)
            : base("tencentcloud:Teo/functionComponentBinding:FunctionComponentBinding", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/tencentcloudstack",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing FunctionComponentBinding resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static FunctionComponentBinding Get(string name, Input<string> id, FunctionComponentBindingState? state = null, CustomResourceOptions? options = null)
        {
            return new FunctionComponentBinding(name, id, state, options);
        }
    }

    public sealed class FunctionComponentBindingArgs : global::Pulumi.ResourceArgs
    {
        [Input("functionComponentBindings", required: true)]
        private InputList<Inputs.FunctionComponentBindingFunctionComponentBindingArgs>? _functionComponentBindings;

        /// <summary>
        /// List of function component bindings.
        /// </summary>
        public InputList<Inputs.FunctionComponentBindingFunctionComponentBindingArgs> FunctionComponentBindings
        {
            get => _functionComponentBindings ?? (_functionComponentBindings = new InputList<Inputs.FunctionComponentBindingFunctionComponentBindingArgs>());
            set => _functionComponentBindings = value;
        }

        /// <summary>
        /// Function ID.
        /// </summary>
        [Input("functionId", required: true)]
        public Input<string> FunctionId { get; set; } = null!;

        /// <summary>
        /// Site ID.
        /// </summary>
        [Input("zoneId", required: true)]
        public Input<string> ZoneId { get; set; } = null!;

        public FunctionComponentBindingArgs()
        {
        }
        public static new FunctionComponentBindingArgs Empty => new FunctionComponentBindingArgs();
    }

    public sealed class FunctionComponentBindingState : global::Pulumi.ResourceArgs
    {
        [Input("functionComponentBindings")]
        private InputList<Inputs.FunctionComponentBindingFunctionComponentBindingGetArgs>? _functionComponentBindings;

        /// <summary>
        /// List of function component bindings.
        /// </summary>
        public InputList<Inputs.FunctionComponentBindingFunctionComponentBindingGetArgs> FunctionComponentBindings
        {
            get => _functionComponentBindings ?? (_functionComponentBindings = new InputList<Inputs.FunctionComponentBindingFunctionComponentBindingGetArgs>());
            set => _functionComponentBindings = value;
        }

        /// <summary>
        /// Function ID.
        /// </summary>
        [Input("functionId")]
        public Input<string>? FunctionId { get; set; }

        /// <summary>
        /// Site ID.
        /// </summary>
        [Input("zoneId")]
        public Input<string>? ZoneId { get; set; }

        public FunctionComponentBindingState()
        {
        }
        public static new FunctionComponentBindingState Empty => new FunctionComponentBindingState();
    }
}
