// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Provides a resource to create a apiGateway updateApiAppKey
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as tencentcloud from "@tencentcloud_iac/pulumi";
 *
 * const example = new tencentcloud.apigateway.UpdateApiAppKey("example", {
 *     apiAppId: "app-krljp4wn",
 *     apiAppKey: "APID6JmG21yRCc03h4z16hlsTqj1wpO3dB3ZQcUP",
 * });
 * ```
 */
export class UpdateApiAppKey extends pulumi.CustomResource {
    /**
     * Get an existing UpdateApiAppKey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: UpdateApiAppKeyState, opts?: pulumi.CustomResourceOptions): UpdateApiAppKey {
        return new UpdateApiAppKey(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'tencentcloud:ApiGateway/updateApiAppKey:UpdateApiAppKey';

    /**
     * Returns true if the given object is an instance of UpdateApiAppKey.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is UpdateApiAppKey {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === UpdateApiAppKey.__pulumiType;
    }

    /**
     * Application unique ID.
     */
    declare public readonly apiAppId: pulumi.Output<string>;
    /**
     * Key of the application.
     */
    declare public readonly apiAppKey: pulumi.Output<string>;

    /**
     * Create a UpdateApiAppKey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UpdateApiAppKeyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: UpdateApiAppKeyArgs | UpdateApiAppKeyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as UpdateApiAppKeyState | undefined;
            resourceInputs["apiAppId"] = state?.apiAppId;
            resourceInputs["apiAppKey"] = state?.apiAppKey;
        } else {
            const args = argsOrState as UpdateApiAppKeyArgs | undefined;
            if (args?.apiAppId === undefined && !opts.urn) {
                throw new Error("Missing required property 'apiAppId'");
            }
            if (args?.apiAppKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'apiAppKey'");
            }
            resourceInputs["apiAppId"] = args?.apiAppId;
            resourceInputs["apiAppKey"] = args?.apiAppKey;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(UpdateApiAppKey.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering UpdateApiAppKey resources.
 */
export interface UpdateApiAppKeyState {
    /**
     * Application unique ID.
     */
    apiAppId?: pulumi.Input<string>;
    /**
     * Key of the application.
     */
    apiAppKey?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a UpdateApiAppKey resource.
 */
export interface UpdateApiAppKeyArgs {
    /**
     * Application unique ID.
     */
    apiAppId: pulumi.Input<string>;
    /**
     * Key of the application.
     */
    apiAppKey: pulumi.Input<string>;
}
