// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace TencentCloudIAC.PulumiPackage.Tencentcloud.Mongodb.Inputs
{

    public sealed class ShardingInstanceAddNodeListGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Node role to add. Valid values: `SECONDARY` (Mongod node), `READONLY` (read-only node), `MONGOS` (Mongos node).
        /// </summary>
        [Input("role", required: true)]
        public Input<string> Role { get; set; } = null!;

        /// <summary>
        /// The availability zone for the new node.
        /// </summary>
        [Input("zone", required: true)]
        public Input<string> Zone { get; set; } = null!;

        public ShardingInstanceAddNodeListGetArgs()
        {
        }
        public static new ShardingInstanceAddNodeListGetArgs Empty => new ShardingInstanceAddNodeListGetArgs();
    }
}
