// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { StartCpuExpandArgs, StartCpuExpandState } from "./startCpuExpand";
export type StartCpuExpand = import("./startCpuExpand").StartCpuExpand;
export const StartCpuExpand: typeof import("./startCpuExpand").StartCpuExpand = null as any;
utilities.lazyLoad(exports, ["StartCpuExpand"], () => require("./startCpuExpand"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "tencentcloud:Cdb/startCpuExpand:StartCpuExpand":
                return new StartCpuExpand(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("tencentcloud", "Cdb/startCpuExpand", _module)
