// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";
import * as utilities from "../utilities";

export function pairs(args?: PairsArgs, opts?: pulumi.InvokeOptions): Promise<PairsResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("tencentcloud:Key/pairs:Pairs", {
        "keyId": args.keyId,
        "keyName": args.keyName,
        "projectId": args.projectId,
        "resultOutputFile": args.resultOutputFile,
    }, opts);
}

/**
 * A collection of arguments for invoking Pairs.
 */
export interface PairsArgs {
    keyId?: string;
    keyName?: string;
    projectId?: number;
    resultOutputFile?: string;
}

/**
 * A collection of values returned by Pairs.
 */
export interface PairsResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly keyId?: string;
    readonly keyName?: string;
    readonly keyPairLists: outputs.Key.PairsKeyPairList[];
    readonly projectId?: number;
    readonly resultOutputFile?: string;
}

export function pairsOutput(args?: PairsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<PairsResult> {
    return pulumi.output(args).apply(a => pairs(a, opts))
}

/**
 * A collection of arguments for invoking Pairs.
 */
export interface PairsOutputArgs {
    keyId?: pulumi.Input<string>;
    keyName?: pulumi.Input<string>;
    projectId?: pulumi.Input<number>;
    resultOutputFile?: pulumi.Input<string>;
}
