// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace TencentCloudIAC.PulumiPackage.Tencentcloud.Organization.Outputs
{

    [OutputType]
    public sealed class GetPermissionPoliciesInRoleConfigurationRolePolicyResult
    {
        /// <summary>
        /// Time when the permission policy was added to the role configuration.
        /// </summary>
        public readonly string AddTime;
        /// <summary>
        /// Custom policy content. Only returned for custom policies.
        /// </summary>
        public readonly string RolePolicyDocument;
        /// <summary>
        /// Policy ID.
        /// </summary>
        public readonly int RolePolicyId;
        /// <summary>
        /// Permission policy name.
        /// </summary>
        public readonly string RolePolicyName;
        /// <summary>
        /// Permission policy type. Valid values: `System`: System policy, reuses CAM system policies. `Custom`: Custom policy, written according to CAM permission policy syntax and structure.
        /// </summary>
        public readonly string RolePolicyType;

        [OutputConstructor]
        private GetPermissionPoliciesInRoleConfigurationRolePolicyResult(
            string addTime,

            string rolePolicyDocument,

            int rolePolicyId,

            string rolePolicyName,

            string rolePolicyType)
        {
            AddTime = addTime;
            RolePolicyDocument = rolePolicyDocument;
            RolePolicyId = rolePolicyId;
            RolePolicyName = rolePolicyName;
            RolePolicyType = rolePolicyType;
        }
    }
}
