// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Clb.Outputs
{

    [OutputType]
    public sealed class InstanceSnatIp
    {
        /// <summary>
        /// Snat IP address, If set to empty will auto allocated.
        /// </summary>
        public readonly string? Ip;
        /// <summary>
        /// Snat subnet ID.
        /// </summary>
        public readonly string SubnetId;

        [OutputConstructor]
        private InstanceSnatIp(
            string? ip,

            string subnetId)
        {
            Ip = ip;
            SubnetId = subnetId;
        }
    }
}
