// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace TencentCloudIAC.PulumiPackage.Tencentcloud.Teo.Inputs
{

    public sealed class ConfirmMultiPathGatewayOriginAclMultiPathGatewayOriginAclInfoMultiPathGatewayNextOriginAclAddedAddressGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("ipv4s")]
        private InputList<string>? _ipv4s;

        /// <summary>
        /// IPv4 segment list.
        /// </summary>
        public InputList<string> Ipv4s
        {
            get => _ipv4s ?? (_ipv4s = new InputList<string>());
            set => _ipv4s = value;
        }

        [Input("ipv6s")]
        private InputList<string>? _ipv6s;

        /// <summary>
        /// IPv6 segment list.
        /// </summary>
        public InputList<string> Ipv6s
        {
            get => _ipv6s ?? (_ipv6s = new InputList<string>());
            set => _ipv6s = value;
        }

        public ConfirmMultiPathGatewayOriginAclMultiPathGatewayOriginAclInfoMultiPathGatewayNextOriginAclAddedAddressGetArgs()
        {
        }
        public static new ConfirmMultiPathGatewayOriginAclMultiPathGatewayOriginAclInfoMultiPathGatewayNextOriginAclAddedAddressGetArgs Empty => new ConfirmMultiPathGatewayOriginAclMultiPathGatewayOriginAclInfoMultiPathGatewayNextOriginAclAddedAddressGetArgs();
    }
}
