// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace TencentCloudIAC.PulumiPackage.Tencentcloud.Teo.Inputs
{

    public sealed class SecurityPolicyConfigSecurityConfigGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Custom rule configuration.
        /// </summary>
        [Input("aclConfig")]
        public Input<Inputs.SecurityPolicyConfigSecurityConfigAclConfigGetArgs>? AclConfig { get; set; }

        /// <summary>
        /// Bot configuration.
        /// </summary>
        [Input("botConfig")]
        public Input<Inputs.SecurityPolicyConfigSecurityConfigBotConfigGetArgs>? BotConfig { get; set; }

        [Input("detectLengthLimitConfigs")]
        private InputList<Inputs.SecurityPolicyConfigSecurityConfigDetectLengthLimitConfigGetArgs>? _detectLengthLimitConfigs;

        /// <summary>
        /// Detect length limit configuration.
        /// </summary>
        public InputList<Inputs.SecurityPolicyConfigSecurityConfigDetectLengthLimitConfigGetArgs> DetectLengthLimitConfigs
        {
            get => _detectLengthLimitConfigs ?? (_detectLengthLimitConfigs = new InputList<Inputs.SecurityPolicyConfigSecurityConfigDetectLengthLimitConfigGetArgs>());
            set => _detectLengthLimitConfigs = value;
        }

        /// <summary>
        /// Drop page configuration.
        /// </summary>
        [Input("dropPageConfig")]
        public Input<Inputs.SecurityPolicyConfigSecurityConfigDropPageConfigGetArgs>? DropPageConfig { get; set; }

        /// <summary>
        /// Exception rules configuration.
        /// </summary>
        [Input("exceptConfig")]
        public Input<Inputs.SecurityPolicyConfigSecurityConfigExceptConfigGetArgs>? ExceptConfig { get; set; }

        /// <summary>
        /// Basic access control.
        /// </summary>
        [Input("ipTableConfig")]
        public Input<Inputs.SecurityPolicyConfigSecurityConfigIpTableConfigGetArgs>? IpTableConfig { get; set; }

        /// <summary>
        /// Rate limit configuration.
        /// </summary>
        [Input("rateLimitConfig")]
        public Input<Inputs.SecurityPolicyConfigSecurityConfigRateLimitConfigGetArgs>? RateLimitConfig { get; set; }

        /// <summary>
        /// Slow attack configuration.
        /// </summary>
        [Input("slowPostConfig")]
        public Input<Inputs.SecurityPolicyConfigSecurityConfigSlowPostConfigGetArgs>? SlowPostConfig { get; set; }

        /// <summary>
        /// Layer-7 protection master switch.
        /// </summary>
        [Input("switchConfig")]
        public Input<Inputs.SecurityPolicyConfigSecurityConfigSwitchConfigGetArgs>? SwitchConfig { get; set; }

        [Input("templateConfigs")]
        private InputList<Inputs.SecurityPolicyConfigSecurityConfigTemplateConfigGetArgs>? _templateConfigs;

        /// <summary>
        /// Template configuration.
        /// </summary>
        public InputList<Inputs.SecurityPolicyConfigSecurityConfigTemplateConfigGetArgs> TemplateConfigs
        {
            get => _templateConfigs ?? (_templateConfigs = new InputList<Inputs.SecurityPolicyConfigSecurityConfigTemplateConfigGetArgs>());
            set => _templateConfigs = value;
        }

        /// <summary>
        /// Managed rules configuration.
        /// </summary>
        [Input("wafConfig")]
        public Input<Inputs.SecurityPolicyConfigSecurityConfigWafConfigGetArgs>? WafConfig { get; set; }

        public SecurityPolicyConfigSecurityConfigGetArgs()
        {
        }
        public static new SecurityPolicyConfigSecurityConfigGetArgs Empty => new SecurityPolicyConfigSecurityConfigGetArgs();
    }
}
