// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace TencentCloudIAC.PulumiPackage.Tencentcloud.Vpc
{
    public static class GetPrivateIpAddresses
    {
        /// <summary>
        /// Use this data source to query detailed information of vpc PrivateIpAddresses
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Tencentcloud = Pulumi.Tencentcloud;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var privateIpAddresses = Tencentcloud.Vpc.GetPrivateIpAddresses.Invoke(new()
        ///     {
        ///         VpcId = "vpc-l0dw94uh",
        ///         VpcPrivateIpAddresses = new[]
        ///         {
        ///             "10.0.0.1",
        ///         },
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetPrivateIpAddressesResult> InvokeAsync(GetPrivateIpAddressesArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetPrivateIpAddressesResult>("tencentcloud:Vpc/getPrivateIpAddresses:getPrivateIpAddresses", args ?? new GetPrivateIpAddressesArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to query detailed information of vpc PrivateIpAddresses
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Tencentcloud = Pulumi.Tencentcloud;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var privateIpAddresses = Tencentcloud.Vpc.GetPrivateIpAddresses.Invoke(new()
        ///     {
        ///         VpcId = "vpc-l0dw94uh",
        ///         VpcPrivateIpAddresses = new[]
        ///         {
        ///             "10.0.0.1",
        ///         },
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetPrivateIpAddressesResult> Invoke(GetPrivateIpAddressesInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetPrivateIpAddressesResult>("tencentcloud:Vpc/getPrivateIpAddresses:getPrivateIpAddresses", args ?? new GetPrivateIpAddressesInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to query detailed information of vpc PrivateIpAddresses
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Tencentcloud = Pulumi.Tencentcloud;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var privateIpAddresses = Tencentcloud.Vpc.GetPrivateIpAddresses.Invoke(new()
        ///     {
        ///         VpcId = "vpc-l0dw94uh",
        ///         VpcPrivateIpAddresses = new[]
        ///         {
        ///             "10.0.0.1",
        ///         },
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetPrivateIpAddressesResult> Invoke(GetPrivateIpAddressesInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetPrivateIpAddressesResult>("tencentcloud:Vpc/getPrivateIpAddresses:getPrivateIpAddresses", args ?? new GetPrivateIpAddressesInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetPrivateIpAddressesArgs : global::Pulumi.InvokeArgs
    {
        [Input("privateIpAddresses", required: true)]
        private List<string>? _privateIpAddresses;

        /// <summary>
        /// The private `IP` address list. Each request supports a maximum of `10` batch querying.
        /// </summary>
        public List<string> VpcPrivateIpAddresses
        {
            get => _privateIpAddresses ?? (_privateIpAddresses = new List<string>());
            set => _privateIpAddresses = value;
        }

        /// <summary>
        /// Used to save results.
        /// </summary>
        [Input("resultOutputFile")]
        public string? ResultOutputFile { get; set; }

        /// <summary>
        /// The `ID` of the `VPC`, such as `vpc-f49l6u0z`.
        /// </summary>
        [Input("vpcId", required: true)]
        public string VpcId { get; set; } = null!;

        public GetPrivateIpAddressesArgs()
        {
        }
        public static new GetPrivateIpAddressesArgs Empty => new GetPrivateIpAddressesArgs();
    }

    public sealed class GetPrivateIpAddressesInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("privateIpAddresses", required: true)]
        private InputList<string>? _privateIpAddresses;

        /// <summary>
        /// The private `IP` address list. Each request supports a maximum of `10` batch querying.
        /// </summary>
        public InputList<string> PrivateIpAddresses
        {
            get => _privateIpAddresses ?? (_privateIpAddresses = new InputList<string>());
            set => _privateIpAddresses = value;
        }

        /// <summary>
        /// Used to save results.
        /// </summary>
        [Input("resultOutputFile")]
        public Input<string>? ResultOutputFile { get; set; }

        /// <summary>
        /// The `ID` of the `VPC`, such as `vpc-f49l6u0z`.
        /// </summary>
        [Input("vpcId", required: true)]
        public Input<string> VpcId { get; set; } = null!;

        public GetPrivateIpAddressesInvokeArgs()
        {
        }
        public static new GetPrivateIpAddressesInvokeArgs Empty => new GetPrivateIpAddressesInvokeArgs();
    }


    [OutputType]
    public sealed class GetPrivateIpAddressesResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<string> VpcPrivateIpAddresses;
        public readonly string? ResultOutputFile;
        public readonly string VpcId;
        /// <summary>
        /// The list of private `IP` address information.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetPrivateIpAddressesVpcPrivateIpAddressSetResult> VpcPrivateIpAddressSets;

        [OutputConstructor]
        private GetPrivateIpAddressesResult(
            string id,

            ImmutableArray<string> privateIpAddresses,

            string? resultOutputFile,

            string vpcId,

            ImmutableArray<Outputs.GetPrivateIpAddressesVpcPrivateIpAddressSetResult> vpcPrivateIpAddressSets)
        {
            Id = id;
            VpcPrivateIpAddresses = privateIpAddresses;
            ResultOutputFile = resultOutputFile;
            VpcId = vpcId;
            VpcPrivateIpAddressSets = vpcPrivateIpAddressSets;
        }
    }
}
