// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace TencentCloudIAC.PulumiPackage.Tencentcloud.Vod.Outputs
{

    [OutputType]
    public sealed class GetAdaptiveDynamicStreamingTemplatesTemplateListStreamInfoVideoResult
    {
        /// <summary>
        /// Bitrate of video stream in Kbps. Value range: `0` and `[128, 35000]`. If the value is `0`, the bitrate of the video will be the same as that of the source video.
        /// </summary>
        public readonly int Bitrate;
        /// <summary>
        /// Video stream encoder. Valid values: `Libx264`, `Libx265`, `Av1`.`Libx264`: H.264, `Libx265`: H.265, `Av1`: AOMedia Video 1. Currently, a resolution within 640x480 must be specified for `H.265`. and the `Av1` container only supports mp4.
        /// </summary>
        public readonly string Codec;
        /// <summary>
        /// Fill type. Fill refers to the way of processing a screenshot when its aspect ratio is different from that of the source video. The following fill types are supported: `Stretch`: stretch. The screenshot will be stretched frame by frame to match the aspect ratio of the source video, which may make the screenshot shorter or longer; `Black`: fill with black. This option retains the aspect ratio of the source video for the screenshot and fills the unmatched area with black color blocks. Note: this field may return null, indicating that no valid values can be obtained.
        /// </summary>
        public readonly string FillType;
        /// <summary>
        /// Video frame rate in Hz. Value range: `[0, 60]`. If the value is `0`, the frame rate will be the same as that of the source video.
        /// </summary>
        public readonly int Fps;
        /// <summary>
        /// Maximum value of the height (or short side) of a video stream in px. Value range: `0` and `[128, 4096]`. If both `Width` and `Height` are `0`, the resolution will be the same as that of the source video; If `Width` is `0`, but `Height` is not `0`, `Width` will be proportionally scaled; If `Width` is not `0`, but `Height` is `0`, `Height` will be proportionally scaled; If both `Width` and `Height` are not `0`, the custom resolution will be used. Note: this field may return null, indicating that no valid values can be obtained.
        /// </summary>
        public readonly int Height;
        /// <summary>
        /// Resolution adaption. Valid values: `True`,`False`. `True`: enabled. In this case, `Width` represents the long side of a video, while `Height` the short side; `False`: disabled. In this case, `Width` represents the width of a video, while `Height` the height. Note: this field may return null, indicating that no valid values can be obtained.
        /// </summary>
        public readonly bool ResolutionAdaptive;
        /// <summary>
        /// Maximum value of the width (or long side) of a video stream in px. Value range: `0` and `[128, 4096]`. If both `Width` and `Height` are `0`, the resolution will be the same as that of the source video; If `Width` is `0`, but `Height` is not `0`, `Width` will be proportionally scaled; If `Width` is not `0`, but `Height` is `0`, `Height` will be proportionally scaled; If both `Width` and `Height` are not `0`, the custom resolution will be used. Note: this field may return null, indicating that no valid values can be obtained.
        /// </summary>
        public readonly int Width;

        [OutputConstructor]
        private GetAdaptiveDynamicStreamingTemplatesTemplateListStreamInfoVideoResult(
            int bitrate,

            string codec,

            string fillType,

            int fps,

            int height,

            bool resolutionAdaptive,

            int width)
        {
            Bitrate = bitrate;
            Codec = codec;
            FillType = fillType;
            Fps = fps;
            Height = height;
            ResolutionAdaptive = resolutionAdaptive;
            Width = width;
        }
    }
}
