// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tencentcloud.Tke.Outputs
{

    [OutputType]
    public sealed class ClusterWorkerInstancesList
    {
        public readonly string? FailedReason;
        public readonly string? InstanceId;
        public readonly string? InstanceRole;
        public readonly string? InstanceState;
        public readonly string? LanIp;

        [OutputConstructor]
        private ClusterWorkerInstancesList(
            string? failedReason,

            string? instanceId,

            string? instanceRole,

            string? instanceState,

            string? lanIp)
        {
            FailedReason = failedReason;
            InstanceId = instanceId;
            InstanceRole = instanceRole;
            InstanceState = instanceState;
            LanIp = lanIp;
        }
    }
}
